/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.monitoring.jsonc --include-runtime=false --strict-vars=false --env-interface=MonitoringEnv monitoring-configuration.d.ts` (hash: 99880c0f11a31d334adbbf4434f17dd4)
interface __BaseEnv_MonitoringEnv {
	EVIDENCE: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	BROWSER: BrowserRun;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	SENTRY_ENVIRONMENT: string;
	SENTRY_TRACES_SAMPLE_RATE: string;
	MONITOR_BASE_URL: string;
	MONITOR_EMAIL: string;
	MONITOR_PASSWORD: string;
	MONITOR_OFFICE_ID: string;
	MONITOR_RUN_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/monitoring");
	}
	interface Env extends __BaseEnv_MonitoringEnv {}
}
interface MonitoringEnv extends __BaseEnv_MonitoringEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE" | "MONITOR_BASE_URL" | "MONITOR_EMAIL" | "MONITOR_PASSWORD" | "MONITOR_OFFICE_ID" | "MONITOR_RUN_TOKEN">> {}
}
