/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.data/previews/refactor/wrangler.json --include-runtime=false --strict-vars=false --env-interface=PreviewEnv preview-configuration.d.ts` (hash: 9d7f76046386aaedbe9da39565779a76)
interface __BaseEnv_PreviewEnv {
	VAULT: R2Bucket;
	KNOWLEDGE: VectorizeIndex;
	HYPERDRIVE: Hyperdrive;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	NODE_ENV: string;
	PROCESSORS_ENABLED: string;
	BETTER_AUTH_URL: string;
	SENTRY_ENVIRONMENT: string;
	SENTRY_TRACES_SAMPLE_RATE: string;
	VAULT_STORAGE_BACKEND: string;
	VECTOR_INDEX_BACKEND: string;
	BETTER_AUTH_SECRET: string;
	K5_CREDENTIALS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/web-preview");
	}
	interface Env extends __BaseEnv_PreviewEnv {}
}
interface PreviewEnv extends __BaseEnv_PreviewEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "PROCESSORS_ENABLED" | "BETTER_AUTH_URL" | "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE" | "VAULT_STORAGE_BACKEND" | "VECTOR_INDEX_BACKEND" | "BETTER_AUTH_SECRET" | "K5_CREDENTIALS_KEY">> {}
}
