/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=wrangler.notifications.jsonc --config=wrangler.integrations.jsonc --include-runtime=false --env-interface=CloudflareEnv` (hash: aa5c62d1fbec789e20ba18871aa22504)
interface __BaseEnv_CloudflareEnv {
	VAULT: R2Bucket;
	LUME_HELP: VectorizeIndex;
	KNOWLEDGE: VectorizeIndex;
	HYPERDRIVE: Hyperdrive;
	INTEGRATIONS_QUEUE: Queue;
	LUME_HELP_AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	PROCESSORS_ENABLED: "true";
	SENTRY_ENVIRONMENT: "staging";
	SENTRY_TRACES_SAMPLE_RATE: "0.1";
	NODE_ENV: "production";
	VECTOR_INDEX_BACKEND: "vectorize";
	VAULT_STORAGE_BACKEND: "r2";
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	SESSION_IDLE_SECONDS: string;
	BETTER_AUTH_TRUSTED_ORIGINS: string;
	K5_CREDENTIALS_KEY: string;
	DATABASE_URL: string;
	DATABASE_URL_UNPOOLED: string;
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	GOOGLE_OAUTH_REDIRECT_URI: string;
	GOOGLE_PICKER_APP_ID: string;
	GOOGLE_PICKER_API_KEY: string;
	EXA_API_KEY: string;
	ABACATEPAY_API_KEY: string;
	PROCESSORS: DurableObjectNamespace<import("./src/workers/web").LumeProcessor>;
	CHAT_RUNS: DurableObjectNamespace<import("./src/workers/web").LumeChatRun>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/web");
		durableNamespaces: "LumeProcessor" | "LumeChatRun";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROCESSORS_ENABLED" | "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE" | "NODE_ENV" | "VECTOR_INDEX_BACKEND" | "VAULT_STORAGE_BACKEND" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "SESSION_IDLE_SECONDS" | "BETTER_AUTH_TRUSTED_ORIGINS" | "K5_CREDENTIALS_KEY" | "DATABASE_URL" | "DATABASE_URL_UNPOOLED" | "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_CLIENT_SECRET" | "GOOGLE_OAUTH_REDIRECT_URI" | "GOOGLE_PICKER_APP_ID" | "GOOGLE_PICKER_API_KEY" | "EXA_API_KEY" | "ABACATEPAY_API_KEY">> {}
}
