/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=wrangler.notifications.jsonc --config=wrangler.integrations.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: 15da0025df26ee581060c785333465a5)
interface __BaseEnv_CloudflareEnv {
	VAULT: R2Bucket;
	LUME_HELP: VectorizeIndex;
	KNOWLEDGE: VectorizeIndex;
	HYPERDRIVE: Hyperdrive;
	INTEGRATIONS_QUEUE: Queue;
	FLAGS: Flagship;
	BROWSER: BrowserRun;
	LUME_HELP_AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCOUNT_ID: string;
	FLAGSHIP_APP_ID: string;
	PROCESSORS_ENABLED: string;
	SENTRY_ENVIRONMENT: string;
	SENTRY_TRACES_SAMPLE_RATE: string;
	NODE_ENV: string;
	VECTOR_INDEX_BACKEND: string;
	VAULT_STORAGE_BACKEND: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	SESSION_IDLE_SECONDS: string;
	BETTER_AUTH_TRUSTED_ORIGINS: string;
	K5_CREDENTIALS_KEY: string;
	DATABASE_URL: string;
	DATABASE_URL_UNPOOLED: string;
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	GOOGLE_OAUTH_REDIRECT_URI: string;
	GOOGLE_PICKER_APP_ID: string;
	GOOGLE_PICKER_API_KEY: string;
	EXA_API_KEY: string;
	ABACATEPAY_API_KEY: string;
	PROCESSORS: DurableObjectNamespace<import("./src/workers/web").LumeProcessor>;
	CHAT_RUNS: DurableObjectNamespace<import("./src/workers/web").LumeChatRun>;
	TRADEMARK_RUNS: DurableObjectNamespace<import("./src/workers/web").LumeTrademarkRun>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/web");
		durableNamespaces: "LumeProcessor" | "LumeChatRun" | "LumeTrademarkRun";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "FLAGSHIP_APP_ID" | "PROCESSORS_ENABLED" | "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE" | "NODE_ENV" | "VECTOR_INDEX_BACKEND" | "VAULT_STORAGE_BACKEND" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "SESSION_IDLE_SECONDS" | "BETTER_AUTH_TRUSTED_ORIGINS" | "K5_CREDENTIALS_KEY" | "DATABASE_URL" | "DATABASE_URL_UNPOOLED" | "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_CLIENT_SECRET" | "GOOGLE_OAUTH_REDIRECT_URI" | "GOOGLE_PICKER_APP_ID" | "GOOGLE_PICKER_API_KEY" | "EXA_API_KEY" | "ABACATEPAY_API_KEY">> {}
}
