/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=wrangler.notifications.jsonc --include-runtime=false --env-interface=CloudflareEnv` (hash: 5abdddd6c98d498cb236d1f906a7a609)
interface __BaseEnv_CloudflareEnv {
	VAULT: R2Bucket;
	KNOWLEDGE: VectorizeIndex;
	HYPERDRIVE: Hyperdrive;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	SENTRY_ENVIRONMENT: "staging";
	SENTRY_TRACES_SAMPLE_RATE: "0.1";
	NODE_ENV: "production";
	VECTOR_INDEX_BACKEND: "vectorize";
	VAULT_STORAGE_BACKEND: "r2";
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	DATABASE_PATH: string;
	SESSION_IDLE_SECONDS: string;
	BETTER_AUTH_TRUSTED_ORIGINS: string;
	K5_CREDENTIALS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/web");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE" | "NODE_ENV" | "VECTOR_INDEX_BACKEND" | "VAULT_STORAGE_BACKEND" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "DATABASE_PATH" | "SESSION_IDLE_SECONDS" | "BETTER_AUTH_TRUSTED_ORIGINS" | "K5_CREDENTIALS_KEY">> {}
}
