// Materialize the final legacy schema once; PostgreSQL deployments use db/postgres/*.sql.
import { DatabaseSync } from 'node:sqlite';
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { postgresSql } from '../src/lib/db/postgres';

const legacy = new DatabaseSync(':memory:');
for (const file of readdirSync('db/migrations').filter(file => file.endsWith('.sql')).sort()) {
  legacy.exec(readFileSync(`db/migrations/${file}`, 'utf8'));
}
const rows = legacy.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '%fts%' ORDER BY name").all() as {name:string;sql:string}[];
const output = ['-- PostgreSQL baseline from the complete legacy schema (0000–0020).',
  '-- The legacy files remain only for importing SQLite/D1 backups. Do not apply them to PostgreSQL.'];
const constraints: string[] = [];
function columns(sql: string) {
  const result: string[] = [];
  let depth = 0, quote = '', start = 0;
  for (let index=0; index<sql.length; index++) {
    const char = sql[index];
    if (quote) { if (char===quote) { if (sql[index+1]===quote) index++; else quote=''; } }
    else if (char==="'" || char==='"') quote=char;
    else if (char==='(') depth++;
    else if (char===')') depth--;
    else if (char===',' && depth===0) { result.push(sql.slice(start,index).trim()); start=index+1; }
  }
  result.push(sql.slice(start).trim());
  return result;
}
for (const row of rows) {
  const cleanSql = row.sql.replace(/--[^\r\n]*/g, '');
  const definitions = columns(cleanSql.slice(cleanSql.indexOf('(')+1, cleanSql.lastIndexOf(')')))
    .filter(column => !/^FOREIGN KEY/i.test(column))
    .map(column => column.replace(/\s+REFERENCES\s+(?:"[^"]+"|\w+)\s*\([^)]*\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|RESTRICT|SET NULL|NO ACTION|SET DEFAULT))*/gi, ''))
    .map(column => column
      .replace(/\bINTEGER\b/gi, 'BIGINT').replace(/\bBLOB\b/gi, 'BYTEA')
      .replace(/^("?\w+(?:_at|At|_until)"?)\s+(?:TEXT|DATE)\b/i, '$1 TIMESTAMPTZ')
      .replace(/\bjson_valid\((\w+)\)/g, '($1 IS JSON)')
      .replace(/datetime\('now','\+30 days'\)/g, "CURRENT_TIMESTAMP + INTERVAL '30 days'"));
  if (row.name==='user') {
    const index = definitions.findIndex(column=>column.startsWith('"emailVerified"'));
    definitions[index] = '"emailVerified" BOOLEAN NOT NULL';
  }
  if (['judicial_sync_job','artifact_verification'].includes(row.name)) definitions.push('sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE');
  if (row.name==='vault_document_chunk') definitions.push("search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('portuguese',content)) STORED");
  output.push(postgresSql(`CREATE TABLE "${row.name}" (\n  ${definitions.join(',\n  ')}\n);`));
  const keys = legacy.prepare(`PRAGMA foreign_key_list("${row.name}")`).all() as {id:number;seq:number;table:string;from:string;to:string;on_delete:string;on_update:string}[];
  for (const id of new Set(keys.map(key=>key.id))) {
    const group = keys.filter(key=>key.id===id).sort((a,b)=>a.seq-b.seq);
    constraints.push(`ALTER TABLE "${row.name}" ADD FOREIGN KEY (${group.map(key=>`"${key.from}"`).join(',')}) REFERENCES "${group[0].table}" (${group.map(key=>`"${key.to}"`).join(',')}) ON DELETE ${group[0].on_delete} ON UPDATE ${group[0].on_update} DEFERRABLE INITIALLY IMMEDIATE;`);
  }
}
for (const row of legacy.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name").all() as {sql:string}[]) output.push(postgresSql(`${row.sql};`));
output.push(...constraints,
  "CREATE INDEX vault_chunk_search_idx ON vault_document_chunk USING GIN(search_vector);",
  `CREATE TABLE research_fts (
  judgment_id TEXT NOT NULL REFERENCES research_judgment(id) ON DELETE CASCADE,
  material_version_id TEXT NOT NULL REFERENCES research_material_version(id) ON DELETE CASCADE,
  text_content TEXT NOT NULL,
  search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('portuguese',text_content)) STORED
);`,
  'CREATE INDEX research_text_search_idx ON research_fts USING GIN(search_vector);',
  'CREATE INDEX research_text_version_idx ON research_fts(material_version_id);',
  `CREATE FUNCTION notification_event_capture_gate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.event_type <> 'system.push.test' AND COALESCE((SELECT capture_enabled FROM notification_rollout WHERE office_id=NEW.office_id),1)=0 THEN
    RETURN NULL;
  END IF;
  RETURN NEW;
END;
$$;`,
  'CREATE TRIGGER notification_event_capture_gate BEFORE INSERT ON notification_event FOR EACH ROW EXECUTE FUNCTION notification_event_capture_gate();');
mkdirSync('db/postgres', {recursive:true});
writeFileSync('db/postgres/0001_initial.sql', output.join('\n\n')+'\n');
legacy.close();
console.log(`PostgreSQL baseline: ${rows.length+1} tables.`);
