/**
 * Writes Better Auth's schema to db/migrations/0000_auth.sql.
 *
 * Better Auth builds its own tables through a Kysely migrator that needs a live Node handle on a
 * SQLite file. D1 has no such handle at deploy time, so the schema has to exist as SQL like every
 * other table in this repository. Run this after upgrading better-auth and commit the diff; that
 * diff is the only place an auth schema change becomes reviewable.
 *
 *   pnpm --filter @k5/web exec tsx scripts/dump-auth-schema.ts
 */
import { DatabaseSync } from "node:sqlite";
import { rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getMigrations } from "better-auth/db/migration";
import { createAuth } from "../src/lib/auth-core";

/** Parents before children, so the file also reads in dependency order. */
const TABLE_ORDER = ["user", "session", "account", "verification", "rateLimit"];

const HEADER = `-- Better Auth's own schema, materialised. Generated by scripts/dump-auth-schema.ts.
--
-- Better Auth generates these tables at setup time through its Kysely migrator. That works while a
-- Node process owns a local SQLite file and stops working the moment the database is D1, which has
-- no such handle at deploy time. Writing the schema down makes it apply like every other table and
-- makes an auth schema change reviewable in a diff.
--
-- Do not hand-edit: regenerate after upgrading better-auth.
`;

async function main() {
  const probe = resolve(".data/.auth-schema-probe.sqlite");
  rmSync(probe, { force: true });
  const db = new DatabaseSync(probe);
  try {
    // Throwaway credentials: nothing is served from this database, only its shape is read.
    const auth = createAuth(db, { secret: "x".repeat(48), baseURL: "http://localhost:3000", idleSeconds: 28800 });
    const { runMigrations } = await getMigrations(auth.options);
    await runMigrations();

    const rows = db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL")
      .all() as Array<{ type: string; name: string; tbl_name: string; sql: string }>;

    const rank = (r: { type: string; tbl_name: string }) => {
      const table = TABLE_ORDER.indexOf(r.tbl_name);
      return [r.type === "table" ? 0 : 1, table === -1 ? TABLE_ORDER.length : table] as const;
    };
    rows.sort((a, b) => {
      const [at, ao] = rank(a); const [bt, bo] = rank(b);
      return at - bt || ao - bo || a.name.localeCompare(b.name);
    });

    const body = rows
      .map(r => String(r.sql).trim().replace(/^CREATE (TABLE|INDEX) /i, (_m, kind: string) => `CREATE ${kind.toUpperCase()} IF NOT EXISTS `))
      .map(sql => `${sql};`)
      .join("\n\n");

    writeFileSync(resolve("db/migrations/0000_auth.sql"), `${HEADER}\n${body}\n`);
    console.log(`0000_auth.sql: ${rows.filter(r => r.type === "table").length} tabelas, ${rows.filter(r => r.type === "index").length} índices.`);
  } finally {
    db.close();
    rmSync(probe, { force: true });
  }
}

main().catch(error => { console.error(error); process.exitCode = 1; });
