import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { chromium, expect as playwrightExpect } from '@playwright/test';
import { Pool } from 'pg';
import { extractText } from 'unpdf';
import { z } from 'zod';

const settings = parseEnv(await readFile(process.env.K5_ENV_FILE ?? '.env.local', 'utf8'));
const expect = playwrightExpect.configure({ timeout: 60_000 });
const baseURL = process.env.BASE_URL ?? settings.BETTER_AUTH_URL ?? 'http://localhost:3000';
const databaseUrl = process.env.DATABASE_URL ?? settings.DATABASE_URL;
for (const value of [baseURL, databaseUrl]) if (!value || !['localhost', '127.0.0.1'].includes(new URL(value).hostname)) throw new Error('A validação exige servidor e banco locais.');
const pool = new Pool({ connectionString: databaseUrl });
const browser = await chromium.launch();
const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(60_000);
const output = 'playwright-report/document-pdf';
await mkdir(output, { recursive: true });
const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
try {
  const accountResponse = await context.request.post('/api/auth/sign-up/email', { data: { name: 'Validação PDF', email: `pdf-${randomUUID()}@example.test`, password: `Validação!${randomUUID()}`, officeName: 'Escritório de validação PDF' }, headers: { origin: baseURL } });
  assert.equal(accountResponse.ok(), true);
  const { user } = z.object({ user: z.object({ id: z.string() }) }).parse(await accountResponse.json());
  const office = z.object({ office_id: z.string() }).parse((await pool.query('SELECT office_id FROM office_member WHERE user_id=$1', [user.id])).rows[0]);
  const artifactId = randomUUID(), runId = randomUUID();
  await pool.query("INSERT INTO ai_run(id,office_id,user_id,kind,input,status) VALUES($1,$2,$3,'draft','{}','completed')", [runId, office.office_id, user.id]);
  await pool.query('INSERT INTO ai_artifact(id,office_id,user_id,run_id,title,content) VALUES($1,$2,$3,$4,$5,$6)', [artifactId, office.office_id, user.id, runId, 'Contrato de validação PDF', '# Contrato\n\nTexto inicial para revisão.']);
  await page.goto(`/app/documents/${artifactId}`);
  await page.getByRole('button', { name: 'Agora não', exact: true }).click();
  const editor = page.getByRole('textbox', { name: 'Texto do documento' });
  await expect(editor).toBeVisible();
  await editor.fill('Texto de validação atualizado. Cliente José, R$ 1.250,00.');
  await page.getByRole('button', { name: 'Exportar documento', exact: true }).focus();
  await page.keyboard.press('Enter');
  const downloadPromise = page.waitForEvent('download', { timeout: 120_000 });
  await page.getByRole('button', { name: 'Exportar PDF', exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs(`${output}/contrato.pdf`);
  const { text } = await extractText(new Uint8Array(await readFile(`${output}/contrato.pdf`)), { mergePages: true });
  assert.match(text, /Texto de validação atualizado/);
  await page.keyboard.press('Escape');
  await expect(editor).toBeVisible();
  await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
  const stale = await context.request.get(`/api/artifacts/${artifactId}/export?format=pdf&version=0`);
  assert.equal(stale.status(), 409);
  assert.equal((await context.request.get(`/api/artifacts/${artifactId}/export?format=html`)).status(), 400);
  const anonymous = await browser.newContext({ baseURL });
  assert.equal((await anonymous.request.get(`/api/artifacts/${artifactId}/export?format=pdf`)).status(), 401);
  await anonymous.close();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Exportar documento', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Exportar DOCX', exact: true })).toBeVisible();
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  await page.keyboard.press('Escape');
  await page.route(`**/api/artifacts/${artifactId}/export?format=pdf*`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'A conversão está indisponível. Tente novamente.' }) }));
  await page.getByRole('button', { name: 'Exportar documento', exact: true }).click();
  await page.getByRole('button', { name: 'Exportar PDF', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'A conversão está indisponível' })).toBeVisible();
  await expect(editor).toBeVisible();
  await page.keyboard.press('Escape');
  await page.screenshot({ path: `${output}/erro-mobile.png`, fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PDF verificado: edição salva, download, versão, sessão, teclado, desktop, celular e falha recuperável.');
} catch (error) { await page.screenshot({ path: `${output}/falha.png`, fullPage: true }); throw error; }
finally { await context.close(); await browser.close(); await pool.end(); }
