import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { chromium, expect as playwrightExpect } from '@playwright/test';
import { Pool } from 'pg';
import { extractText } from 'unpdf';
import { PDFDocument } from 'pdf-lib';
import { z } from 'zod';

const settings = parseEnv(await readFile(process.env.K5_ENV_FILE ?? '.env.local', 'utf8'));
const baseURL = process.env.BASE_URL ?? settings.BETTER_AUTH_URL;
const databaseURL = process.env.DATABASE_URL ?? settings.DATABASE_URL;
if (!baseURL || !databaseURL || [baseURL, databaseURL].some(url => !['localhost','127.0.0.1'].includes(new URL(url).hostname))) throw new Error('Use servidor e banco locais.');
const expect = playwrightExpect.configure({ timeout: 60_000 });
const pool = new Pool({ connectionString: databaseURL });
const browser = await chromium.launch();
const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage(); page.setDefaultTimeout(60_000);
const output = 'playwright-report/honorario-charge'; await mkdir(output, { recursive: true });
const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
try {
  const signup = await context.request.post('/api/auth/sign-up/email', { headers: { origin: baseURL }, data: { name: 'Ana Validação', email: `${randomUUID()}@example.test`, password: `Validação!${randomUUID()}`, officeName: 'Cobrança Validação' } });
  assert.equal(signup.ok(), true);
  const { user } = z.object({ user: z.object({ id: z.string() }) }).parse(await signup.json());
  const office = z.object({ office_id: z.string() }).parse((await pool.query('SELECT office_id FROM office_member WHERE user_id=$1', [user.id])).rows[0]);
  const clientId = randomUUID();
  await pool.query("INSERT INTO crm_client(id,office_id,name,stage,created_at,updated_at) VALUES($1,$2,'Maria Cliente','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)", [clientId, office.office_id]);
  const create = await context.request.post('/api/honorarios/create', { headers: { origin: baseURL }, data: { clientId, title: 'Contrato de teste', installments: [{ amountCents: 125000, dueOn: '2035-01-10' }], idempotencyKey: randomUUID() } });
  assert.equal(create.ok(), true);
  const detail = z.object({ agreement: z.object({ id: z.string() }), installments: z.array(z.object({ id: z.string() })) }).parse(await create.json());
  const installmentId = detail.installments[0].id;
  await page.goto(`/app/honorarios?agreementId=${detail.agreement.id}`);
  await page.getByRole('button', { name: 'Agora não', exact: true }).click();
  await page.getByRole('button', { name: 'Preparar cobrança da parcela 1' }).focus(); await page.keyboard.press('Enter');
  await page.getByLabel('Chave PIX', { exact: true }).fill('financeiro@example.test');
  await page.getByLabel('Instruções de pagamento', { exact: true }).fill('Titular Ana. Confira os dados antes de pagar.');
  const boleto = await PDFDocument.create(); boleto.addPage();
  await page.getByLabel('Boleto em PDF (até 10 MB)', { exact: true }).setInputFiles({ name: 'boleto-teste.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await boleto.save()) });
  await expect(page.getByText('Boleto anexado ao Cofre.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Salvar cobrança', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Baixar PDF', exact: true })).toBeEnabled();
  const downloadPromise = page.waitForEvent('download', { timeout: 120_000 });
  await page.getByRole('button', { name: 'Baixar PDF', exact: true }).click();
  await (await downloadPromise).saveAs(`${output}/cobranca.pdf`);
  const { text } = await extractText(new Uint8Array(await readFile(`${output}/cobranca.pdf`)), { mergePages: true });
  assert.match(text, /Maria Cliente/); assert.match(text, /1\.250,00/); assert.match(text, /financeiro@example.test/);
  await page.getByRole('button', { name: 'Registrar envio realizado', exact: true }).click();
  await expect(page.getByText('Envio registrado no histórico.', { exact: true })).toBeVisible();
  await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Chave PIX', { exact: true }).focus();
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  assert.equal((await context.request.get(`/api/honorarios/charges/${installmentId}/pdf?version=0`)).status(), 409);
  const anonymous = await browser.newContext({ baseURL });
  assert.equal((await anonymous.request.get(`/api/honorarios/charges/${installmentId}/pdf?version=1`)).status(), 401); await anonymous.close();
  const paid = await context.request.post('/api/honorarios/receive', { headers: { origin: baseURL }, data: { installmentId, amountCents: 125000, receivedOn: '2026-01-01', method: 'pix', idempotencyKey: randomUUID() } });
  assert.equal(paid.ok(), true);
  assert.equal((await context.request.get(`/api/honorarios/charges/${installmentId}/pdf?version=1`)).status(), 409);
  assert.deepEqual(errors, []);
  console.log('Cobrança verificada: PIX, boleto, PDF, histórico, teclado, desktop, celular e bloqueio após quitação.');
} catch (error) { await page.screenshot({ path: `${output}/falha.png`, fullPage: true }); throw error; }
finally { await context.close(); await browser.close(); await pool.end(); }
