import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { chromium, expect as playwrightExpect } from '@playwright/test';
import { Pool } from 'pg';
import { PDFDocument } from 'pdf-lib';
import { z } from 'zod';
import { portalManageDto } from '../src/lib/client-portal/contracts';

const settings = parseEnv(await readFile(process.env.K5_ENV_FILE ?? '.env.local', 'utf8'));
const baseURL = process.env.BASE_URL ?? settings.BETTER_AUTH_URL;
const databaseURL = process.env.DATABASE_URL ?? settings.DATABASE_URL;
if (!baseURL || !databaseURL || [baseURL,databaseURL].some(url => !['localhost','127.0.0.1'].includes(new URL(url).hostname))) throw new Error('Use servidor e banco locais.');
const pool = new Pool({ connectionString: databaseURL });
const browser = await chromium.launch();
const office = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const client = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const officePage = await office.newPage(), clientPage = await client.newPage();
for (const page of [officePage,clientPage]) page.setDefaultTimeout(90_000);
const expect = playwrightExpect.configure({ timeout: 90_000 });
const output = 'playwright-report/client-portal'; await mkdir(output, { recursive: true });
const errors: string[] = []; for (const page of [officePage,clientPage]) page.on('pageerror', error => errors.push(error.message));
try {
  const signup = await office.request.post('/api/auth/sign-up/email', { headers: { origin: baseURL }, data: { name: 'Ana Portal', email: `${randomUUID()}@office.test`, password: `Validação!${randomUUID()}`, officeName: 'Escritório Portal' } });
  assert.equal(signup.ok(), true);
  const { user } = z.object({ user: z.object({ id: z.string() }) }).parse(await signup.json());
  const membership = z.object({ office_id: z.string() }).parse((await pool.query('SELECT office_id FROM office_member WHERE user_id=$1', [user.id])).rows[0]);
  const clientId = randomUUID(), email = `${randomUUID()}@client.test`, password = `Cliente!${randomUUID()}`;
  await pool.query("INSERT INTO crm_client(id,office_id,name,email,stage,created_at,updated_at) VALUES($1,$2,'Maria Portal',$3,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)", [clientId, membership.office_id, email]);
  const artifactId = randomUUID(), runId = randomUUID();
  await pool.query("INSERT INTO ai_run(id,office_id,user_id,kind,input,status) VALUES($1,$2,$3,'draft','{}','completed')", [runId, membership.office_id, user.id]);
  await pool.query('INSERT INTO ai_artifact(id,office_id,user_id,run_id,title,content) VALUES($1,$2,$3,$4,$5,$6)', [artifactId, membership.office_id, user.id, runId, 'Contrato Portal', '# Contrato\n\nVersão publicada para Maria.']);
  await officePage.goto(`/app/agenda/clients/${clientId}`);
  await officePage.getByRole('button', { name: 'Agora não', exact: true }).click();
  await officePage.getByRole('button', { name: 'Convidar cliente', exact: true }).click();
  const invitation = await officePage.getByLabel('Link do convite', { exact: true }).inputValue(); assert.match(invitation, /\/client\/invite\//);
  await officePage.getByLabel('Publicar documento do Lume em PDF', { exact: true }).selectOption(artifactId);
  await officePage.getByRole('button', { name: 'Publicar versão em PDF', exact: true }).click();
  await expect(officePage.getByText('A versão selecionada foi publicada em PDF para este cliente.', { exact: true })).toBeVisible();
  const create = await office.request.post('/api/honorarios/create', { headers: { origin: baseURL }, data: { clientId, title: 'Honorários Portal', notes: 'Nota privada', installments: [{ amountCents: 50000, dueOn: '2035-01-10' }], idempotencyKey: randomUUID() } });
  const detail = z.object({ installments: z.array(z.object({ id: z.string() })) }).parse(await create.json()); const installmentId = detail.installments[0].id;
  assert.equal((await office.request.post('/api/honorarios/charge-prepare', { headers: { origin: baseURL }, data: { installmentId, version: 0, pixKey: 'pix@office.test', idempotencyKey: randomUUID() } })).ok(), true);
  assert.equal((await office.request.post('/api/client-portal/manage', { headers: { origin: baseURL }, data: { operation: 'publish-charge', data: { clientId, installmentId, version: 1 } } })).ok(), true);
  await clientPage.goto(invitation);
  await clientPage.getByLabel('Nova senha', { exact: true }).fill(password); await clientPage.getByLabel('Confirmar nova senha', { exact: true }).fill(password);
  const signupResponse = clientPage.waitForResponse(response => response.url().includes('/api/client-portal/invitations/') && response.request().method() === 'POST');
  await clientPage.getByRole('button', { name: 'Criar acesso ao portal', exact: true }).click();
  const clientSignup = await signupResponse;
  assert.equal(clientSignup.ok(), true, `Cadastro: ${clientSignup.status()}`);
  assert.ok((await client.cookies()).some(cookie => cookie.name.includes('session_token')), 'o cadastro deve entregar o cookie de sessão');
  await expect(clientPage.getByRole('heading', { name: 'Portal do cliente', exact: true })).toBeVisible();
  await expect(clientPage.getByRole('link', { name: 'Contrato Portal.pdf', exact: true })).toBeVisible();
  await expect(clientPage.getByRole('link', { name: 'Baixar cobrança em PDF', exact: true })).toBeVisible();
  assert.equal((await client.request.post('/api/honorarios/list', { headers: { origin: baseURL }, data: {} })).status(), 403);
  const account = (await pool.query('SELECT id,"accountKind" FROM "user" WHERE email=$1', [email])).rows[0];
  assert.equal(account.accountKind, 'client');
  assert.equal((await pool.query('SELECT COUNT(*)::int AS n FROM office_member WHERE user_id=$1', [account.id])).rows[0].n, 0);
  const fileURL = await clientPage.getByRole('link', { name: 'Contrato Portal.pdf', exact: true }).getAttribute('href'); assert.ok(fileURL);
  assert.equal((await client.request.get(fileURL)).status(), 200);
  await clientPage.getByRole('button', { name: 'Enviar comprovante desta parcela', exact: true }).click();
  const proof = await PDFDocument.create(); proof.addPage();
  await clientPage.getByLabel('Arquivo para enviar', { exact: true }).setInputFiles({ name: 'comprovante.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await proof.save()) });
  await clientPage.getByRole('button', { name: 'Enviar arquivo ao escritório', exact: true }).click();
  await expect(clientPage.getByText('Comprovante enviado. O escritório fará a conferência do pagamento.', { exact: true })).toBeVisible();
  await clientPage.screenshot({ path: `${output}/cliente-desktop.png`, fullPage: true });
  await clientPage.setViewportSize({ width: 390, height: 844 }); await clientPage.screenshot({ path: `${output}/cliente-mobile.png`, fullPage: true });
  assert.equal(await clientPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  await officePage.getByRole('button', { name: 'Atualizar portal', exact: true }).click();
  await expect(officePage.getByRole('link', { name: 'comprovante.pdf', exact: true })).toBeVisible();
  await officePage.getByRole('heading', { name: 'Portal do cliente', exact: true }).scrollIntoViewIfNeeded();
  await officePage.screenshot({ path: `${output}/escritorio-desktop.png`, fullPage: true });
  await officePage.setViewportSize({ width: 390, height: 844 }); await officePage.getByRole('heading', { name: 'Portal do cliente', exact: true }).scrollIntoViewIfNeeded();
  await officePage.screenshot({ path: `${output}/escritorio-mobile.png`, fullPage: true });
  assert.equal(await officePage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  const managed = portalManageDto.parse(await (await office.request.get(`/api/client-portal/manage?clientId=${clientId}`)).json()); assert.ok(managed.access);
  await officePage.getByRole('button', { name: 'Revogar acesso ao portal', exact: true }).click();
  await expect(officePage.getByText('Acesso e convite revogados.', { exact: true })).toBeVisible();
  assert.equal((await client.request.get(fileURL)).status(), 404);
  assert.equal((await client.request.get(`/api/client-portal/${managed.access.id}`)).status(), 404);
  assert.deepEqual(errors, []);
  console.log('Portal verificado: convite, conta sem escritório, PDF publicado, cobrança, comprovante, isolamento, revogação, desktop e celular.');
} catch (error) { await clientPage.screenshot({ path: `${output}/falha-cliente.png`, fullPage: true }); await officePage.screenshot({ path: `${output}/falha-escritorio.png`, fullPage: true }); throw error; }
finally { await office.close(); await client.close(); await browser.close(); await pool.end(); }
