/** Local UI verification with the existing stable validation account; removes only its own test vote. */
import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { database as db } from '../src/lib/database';

process.loadEnvFile('.env.local');
const baseURL = process.env.BASE_URL ?? 'http://localhost:3000';
if (!['localhost', '127.0.0.1'].includes(new URL(baseURL).hostname)) throw new Error('Local verification only');
const email = process.env.FEEDBACK_TEST_EMAIL ?? 'admin@advocacia.test';
const password = process.env.FEEDBACK_TEST_PASSWORD ?? 'SenhaForte123!@#456';
const marker = `Verificação local ${randomUUID()}`;
const person = (await db.prepare('SELECT id FROM user WHERE email=?').get(email)) as { id: string } | undefined;
if (!person) throw new Error('Stable validation account missing');
const existing = (await db.prepare('SELECT id FROM model_feedback WHERE user_id=?').get(person.id));
if (existing) throw new Error('Existing real feedback preserved; use a different stable validation account');
const dir = resolve('playwright-report/feedback');
await mkdir(dir, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
try {
  expect((await context.request.get('/api/feedback')).status()).toBe(401);
  expect((await context.request.get('/api/feedback/files/a/memo')).status()).toBe(401);
  expect((await context.request.get('/api/platform/feedback')).status()).toBe(401);
  await page.goto('/sign-in');
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.waitForURL('**/app/command-center');
  await page.getByRole('link', { name: 'Avaliar respostas', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Avaliar respostas', exact: true })).toBeVisible();
  await expect(page.getByText('Mercury 2.5', { exact: true })).toHaveCount(0);
  const blind = await (await context.request.get('/api/feedback')).json();
  const sourcesHref = `/api/feedback/files/sources/zip?campaign=${encodeURIComponent(blind.campaignId)}`;
  await expect(page.getByRole('link', { name: 'Baixar os 13 documentos de origem', includeHidden: true })).toHaveAttribute('href', sourcesHref);
  expect((await context.request.get(sourcesHref)).status()).toBe(200);
  expect((await context.request.get('/api/feedback/files/sources/zip?campaign=old-round')).status()).toBe(409);
  expect(JSON.stringify(blind)).not.toMatch(/mercury|deepseek|inception|muse spark|inputTokens|outputTokens/i);
  expect((await context.request.post('/api/feedback', { headers: { origin: 'https://evil.test' }, data: {} })).status()).toBe(403);
  const doc = await context.request.get('/api/feedback/files/a/memo');
  expect(doc.ok()).toBe(true);
  expect(doc.headers()['content-disposition']).toContain('resposta-a');
  expect(doc.headers()['cache-control']).toContain('no-store');
  await page.getByRole('region', { name: 'Memorando da Resposta A' }).focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('region', { name: 'Memorando da Resposta A' })).toBeFocused();
  await page.screenshot({ path: resolve(dir, 'desktop-blind.png') });
  await page.getByRole('group', { name: 'Prévia da Resposta A' }).getByRole('button', { name: 'Planilha' }).click();
  await expect(page.getByRole('region', { name: 'Planilha da Resposta A' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: resolve(dir, 'mobile-blind.png') });
  await page.getByRole('button', { name: 'Mais', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Avaliar respostas', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Tema' }).selectOption('dark');
  await page.keyboard.press('Escape');
  await page.screenshot({ path: resolve(dir, 'mobile-dark.png') });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('combobox', { name: 'Tema' }).selectOption('light');
  await page.getByRole('combobox', { name: 'Clareza da Resposta A' }).selectOption('4');
  await page.getByRole('combobox', { name: 'Utilidade da Resposta B' }).selectOption('3');
  await page.getByRole('radio', { name: 'Empate', exact: true }).check();
  await page.getByLabel('O que mais pesou na sua escolha?', { exact: false }).fill(marker);
  await page.getByRole('checkbox', { name: 'Examinei as duas respostas antes de escolher.' }).check();
  const consent = page.getByRole('checkbox', { name: 'Autorizo usar minhas notas', exact: false });
  await expect(consent).not.toBeChecked();
  await consent.check();
  await page.route('**/api/feedback', route => route.request().method() === 'POST' ? route.abort() : route.continue());
  await page.getByRole('button', { name: 'Enviar avaliação e revelar modelos' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Suas notas continuam aqui' })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Clareza da Resposta A' })).toHaveValue('4');
  await page.screenshot({ path: resolve(dir, 'submit-error.png') });
  await page.unroute('**/api/feedback');
  await page.getByRole('button', { name: 'Enviar avaliação e revelar modelos' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Avaliação salva' })).toBeVisible();
  const revealed = await (await context.request.get('/api/feedback')).json();
  expect(revealed.responses).toHaveLength(2);
  for (const response of revealed.responses) await expect(page.getByText(response.identity.name, { exact: true })).toBeVisible();
  await expect(page.getByRole('radio', { name: 'Empate', exact: true })).toBeDisabled();
  await page.screenshot({ path: resolve(dir, 'desktop-revealed.png') });
  await page.reload();
  await expect(page.getByText('Sua avaliação está salva.', { exact: false })).toBeVisible();
  const exported = await context.request.get('/api/platform/feedback');
  expect(exported.status()).toBe(200);
  expect((await exported.json()).votes.some((vote: { comment: string }) => vote.comment === marker)).toBe(true);
  const datasetResponse = await context.request.get('/api/platform/feedback?format=dataset');
  expect(datasetResponse.status()).toBe(200);
  expect(datasetResponse.headers()['cache-control']).toContain('no-store');
  const dataset = await datasetResponse.json();
  expect(dataset.trainingReady).toBe(false);
  expect(dataset.annotations.some((a: { comment: string; preferenceCandidate: unknown }) => a.comment === marker && a.preferenceCandidate === null)).toBe(true);
  expect(JSON.stringify(dataset)).not.toContain(person.id);
  expect((await (await context.request.get('/api/platform/feedback?history=1')).json()).length).toBeGreaterThanOrEqual(1);
  await page.goto('/platform/feedback');
  await expect(page.getByText(marker, { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(dir, 'platform-results.png') });
  expect(errors).toEqual([]);
  console.log('Feedback verified: blind desktop/mobile, keyboard, dark mode, private downloads, CSRF, retry, persistence, reveal and admin export.');
} finally {
  await browser.close();
  (await db.prepare('DELETE FROM model_feedback WHERE user_id=? AND comment=?').run(person.id, marker));
  (await db.close());
}
