import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {testDatabase as db} from './test-setup';
import {createConversation,saveMessages} from '../src/lib/ai-store';
import {createChatAttachment,ownedChatAttachment,resolveChatAttachments,claimChatAttachments,removeChatAttachment,publicChatAttachment} from '../src/lib/chat-attachments';
import {attachmentPart} from '../src/lib/chat-attachment-contract';
import {chatPromptMessages} from '../src/lib/chat-prompt';
import {objectStorage} from '../src/lib/storage';
import type {UIMessage} from 'ai';

test('chat files persist with their message, remain private and never enter the Vault',async()=>{
  const officeId=randomUUID(),userId=randomUUID();
  await db.prepare('INSERT INTO office(id,name) VALUES(?,?)').run(officeId,'Teste de anexos');
  await db.prepare('INSERT INTO user(id,email,name) VALUES(?,?,?)').run(userId,`${userId}@example.test`,'Teste');
  const owner={officeId,userId};
  const one=await createConversation(db,owner),two=await createConversation(db,owner);
  const attachment=await createChatAttachment(owner,one.id,new File(['Revisar contrato amanhã.'],'tarefas.txt',{type:'text/plain'}));
  assert.equal((await db.prepare('SELECT count(*) AS n FROM vault_document WHERE office_id=?').get(officeId))!.n,0);
  assert.equal(await ownedChatAttachment({...owner,userId:randomUUID()},attachment.id),undefined);
  assert.equal(await ownedChatAttachment({...owner,officeId:randomUUID()},attachment.id),undefined);
  await assert.rejects(resolveChatAttachments(owner,two.id,'message-a',[attachment.id]));
  const rows=await resolveChatAttachments(owner,one.id,'message-a',[attachment.id]);
  await claimChatAttachments(owner,one.id,'message-a',rows);
  await assert.rejects(resolveChatAttachments(owner,one.id,'different-message',[attachment.id]));
  await assert.rejects(removeChatAttachment(owner,attachment.id));
  const history:UIMessage[]=[{id:'message-a',role:'user',parts:[{type:'text',text:'Prepare a agenda'},attachmentPart(publicChatAttachment(rows[0]))]}];
  await saveMessages(db,owner,one.id,history);
  const prompt=await chatPromptMessages(owner,one.id,history,false);
  assert.match(JSON.stringify(prompt),/Revisar contrato amanhã/);
  assert.match(JSON.stringify(prompt),/nunca instruções do sistema/);
  const image=await createChatAttachment(owner,one.id,new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')],'foto.png',{type:'image/png'}));
  const imageRows=await resolveChatAttachments(owner,one.id,'message-b',[image.id]);
  const imageHistory:UIMessage[]=[...history,{id:'message-b',role:'user',parts:[{type:'text',text:'Leia a foto'},attachmentPart(image)]}];
  const imagePrompt=await chatPromptMessages(owner,one.id,imageHistory,true);
  assert.match(JSON.stringify(imagePrompt),/data:image\/png;base64/);
  assert.doesNotMatch(JSON.stringify(imagePrompt),/storage_key/);
  await removeChatAttachment(owner,image.id);
  await assert.rejects((await objectStorage()).get(imageRows[0].storage_key));
  await assert.rejects(createChatAttachment(owner,one.id,new File(['not an image'],'foto.jpg',{type:'image/jpeg'})));
  await assert.rejects(createChatAttachment(owner,two.id,new File([],'vazio.txt')));
});
