import { showCanvas, openModules } from './support/shell';
import { test } from '@e2e-dev/web';
import { expect } from 'e2e';
import { overflowsHorizontally } from './support/fixtures';

test('o shell mantém a marca Lume e todos os destinos no desktop e no celular', { session: 'admin' }, async ({ app, screen, browser }) => {
  await app.open('/app');
  await expect(browser).toHaveURL(/\/app\/command-center$/);
  await expect(screen.getByRole('complementary', 'Lume', { exact: true })).toBeVisible();
  await expect(screen.getByRole('navigation', 'Abas do canvas').getByRole('link', 'Início', { exact: true })).toBeVisible();
  await openModules({ screen, browser });
  await expect(screen.getByRole('button', 'Casos e módulos')).toHaveAttribute('aria-expanded', 'true');
  const menu = screen.getByRole('navigation', 'Casos e módulos');
  for (const label of ['Todos os casos', 'Tarefas', 'Agenda', 'Clientes', 'Mensagens', 'Plano']) await expect(menu.getByRole('link', label, { exact: true })).toBeVisible();
  await browser.keyboard.press('Escape');
  await expect(screen.getByRole('button', 'Casos e módulos')).toBeFocused();
  await screen.getByRole('button', 'Casos e módulos').press('Enter');
  await expect(menu).toBeVisible();
  await menu.getByRole('link', 'Plano', { exact: true }).tap();
  await expect(screen.getByRole('heading', 'Plano', { level: 1 })).toBeVisible({ timeout: 30_000 });
  expect(await browser.evaluate(() => document.documentElement.outerHTML.includes('Tises'))).toBe(false);
  await browser.setViewport({ width: 390, height: 844 });
  await app.open('/app');
  await expect(screen.getByRole('textbox', 'Pergunte ao Lume')).toBeVisible();
  await showCanvas({ screen, browser });
  await expect(screen.getByRole('button', /^Mais opções(?:,|$)/)).toBeVisible();
  await openModules({ screen, browser });
  await menu.getByRole('link', 'Todos os casos', { exact: true }).tap();
  await expect(browser).toHaveURL('/app/vault');
  expect(await browser.evaluate(overflowsHorizontally)).toBe(false);
});
