import { test } from '@e2e-dev/web';
import { expect } from 'e2e';
import { overflowsHorizontally } from './support/fixtures';

test('o shell mantém a marca Lume e todos os destinos no desktop e no celular', { session: 'admin' }, async ({ app, screen, browser }) => {
  await app.open('/app');
  await expect(browser).toHaveURL(/\/app\/command-center$/);
  await expect(screen.getByRole('complementary', 'Lume', { exact: true })).toBeVisible();
  await expect(screen.getByRole('navigation', 'Abas do canvas').getByRole('button', 'Início', { exact: true })).toBeVisible();
  await screen.getByRole('button', 'Abrir módulos').tap();
  await expect(screen.getByRole('button', 'Abrir módulos')).toHaveAttribute('aria-expanded', 'true');
  const menu = screen.getByRole('navigation', 'Módulos');
  for (const label of ['Lume', 'Cofre', 'Mensagens', 'Plano']) await expect(menu.getByRole('button', label, { exact: true })).toBeVisible();
  await browser.keyboard.press('Escape');
  await expect(screen.getByRole('button', 'Abrir módulos')).toBeFocused();
  await screen.getByRole('button', 'Abrir módulos').press('Enter');
  await expect(menu).toBeVisible();
  await menu.getByRole('button', 'Plano', { exact: true }).tap();
  await expect(screen.getByText('Plano Lume').first()).toBeVisible();
  expect(await browser.evaluate(() => document.documentElement.outerHTML.includes('Tises'))).toBe(false);
  await browser.setViewport({ width: 390, height: 844 });
  await app.open('/app');
  await expect(screen.getByRole('textbox', 'Pergunte ao Lume')).toBeVisible();
  await screen.getByRole('navigation', 'Alternar conversa e canvas').getByRole('button', 'Canvas').tap();
  await expect(screen.getByRole('button', 'Abrir módulos')).toBeVisible();
  await screen.getByRole('button', 'Abrir módulos').tap();
  await menu.getByRole('button', 'Cofre', { exact: true }).tap();
  await expect(browser).toHaveURL('/app/vault');
  expect(await browser.evaluate(overflowsHorizontally)).toBe(false);
});
