import { randomUUID } from 'node:crypto';
import { test } from '@e2e-dev/web';
import { expect } from 'e2e';
import { calculationsList, savedCalculation } from '../src/lib/calc/contracts';
import { feeQuoteListDto } from '../src/lib/honorarios/pricing';
import { honorarioDetailDto } from '../src/lib/honorarios/contracts';
import { ApiSession, uniqueAccount } from './support/accounts';
import { signInWithSession } from './support/sign-in';
import { overflowsHorizontally } from './support/fixtures';

test('Calc: consumidor, versões, tributo federal, proposta OAB e parcelas no desktop e celular', { timeout: 360_000 }, async ({ app, screen, browser }) => {
  const api = await new ApiSession(app.baseUrl!).signIn(uniqueAccount('Calc'));
  await api.json('/api/agenda/clients/create', { json: { name: 'Cliente Calc', stage: 'active', idempotencyKey: randomUUID() } });
  const list = async () => calculationsList.parse(await api.json('/api/calc/list', { json: {} }));
  const noOverflow = async () => expect(await browser.evaluate(overflowsHorizontally)).toBe(false);
  await signInWithSession({ app, screen, browser }, api);
  await app.open('/app/calc');
  await expect(screen.getByText('Nenhum cálculo salvo para esta busca.')).toBeVisible();
  await app.screenshot('calc-desktop');
  for (const name of ['Correção de valores', 'Trabalhista', 'Revisional bancário', 'Pensão alimentícia', 'Aluguel', 'Consumidor', 'Tributário']) {
    await screen.getByRole('button', new RegExp(`^${name}`)).tap();
    await expect(screen.getByRole('heading', name, { exact: true })).toBeVisible();
    await screen.getByRole('button', 'Voltar aos cálculos').tap();
  }
  await screen.getByRole('button', /^Consumidor/).focus();
  await browser.keyboard.press('Enter');
  await screen.getByLabel('Título do cálculo').fill('Restituição de cobrança');
  await screen.getByLabel('Data-base', { exact: true }).fill('2025-03-01');
  await screen.getByLabel('Forma de restituição').selectOption({ value: 'double' });
  await screen.getByLabel('Fundamento da restituição e da hipótese escolhida').fill('Excesso pago e dobro conforme título judicial.');
  await screen.getByLabel('Parcela 1: data do pagamento indevido').fill('2025-01-01');
  await screen.getByLabel('Parcela 1: valor (R$)').fill('100,00');
  await screen.getByRole('button', 'Adicionar pagamento').tap();
  await screen.getByLabel('Pagamento 1: data').fill('2025-02-01');
  await screen.getByLabel('Pagamento 1: valor (R$)').fill('50,00');
  await screen.getByRole('button', 'Conferir cálculo').tap();
  await expect(screen.getByTestId('calc-total')).toHaveText(/150,00/);
  await noOverflow();
  await screen.getByRole('button', 'Salvar cálculo', { exact: true }).tap();
  await expect(screen.getByRole('button', 'Revisar parâmetros')).toBeVisible();
  const first = (await list()).items[0];
  expect(first.totalCents).toBe(15000);
  for (const format of ['json', 'csv', 'pdf']) {
    const response = await api.request(`/api/calc/${first.id}/export?version=1&format=${format}`);
    expect(response.status).toBe(200);
    if (format === 'pdf') expect(Buffer.from(await response.arrayBuffer()).subarray(0, 5).toString()).toBe('%PDF-');
    else expect((await response.text()).length).toBeGreaterThan(100);
  }
  await screen.getByRole('button', 'Revisar parâmetros').tap();
  await screen.getByLabel('Parcela 1: valor (R$)').fill('200,00');
  await screen.getByRole('button', 'Salvar nova versão').tap();
  await expect(screen.getByTestId('calc-total')).toHaveText(/350,00/);
  await screen.getByLabel('Versão', { exact: true }).selectOption({ value: '1' });
  await expect(screen.getByTestId('calc-total')).toHaveText(/150,00/);
  const historical = savedCalculation.parse(await api.json('/api/calc/get', { json: { id: first.id, version: 1 } }));
  expect(historical.latestVersion).toBe(2);
  expect(historical.result.totalCents).toBe(15000);

  await screen.getByRole('link', 'Usar resultado como base de honorários').tap();
  await expect(screen.getByRole('heading', 'Propostas e contratos')).toBeVisible({ timeout: 60_000 });
  await expect(screen.getByLabel('Componente 1: base (R$)')).toHaveValue('150,00');
  await screen.getByRole('button', 'Cliente (obrigatório)').tap();
  await screen.getByRole('button', 'Cliente Calc', { exact: true }).tap();
  await screen.getByLabel('Título da proposta').fill('Atuação consumidor PE');
  await screen.getByLabel('Atividade na tabela OAB 2026').selectOption({ index: 1 });
  await expect(screen.getByRole('link', /Abrir OAB-PE/)).toBeVisible();
  await screen.getByLabel('UF do serviço').selectOption({ value: 'RS' });
  await screen.getByLabel('Atividade na tabela OAB 2026').selectOption({ index: 1 });
  await expect(screen.getByRole('link', /Abrir OAB-RS/)).toBeVisible();
  await screen.getByLabel('Escopo, atos e instâncias incluídos').fill('Consulta e análise documental do caso.');
  await screen.getByLabel('Condições de pagamento, despesas e hipótese de acordo').fill('Três parcelas após aprovação da contratação.');
  await screen.getByRole('button', 'Salvar proposta', { exact: true }).tap();
  await expect(screen.getByRole('link', 'Baixar proposta PDF')).toBeVisible();
  const proposal = feeQuoteListDto.parse(await api.json('/api/honorarios/quote-list', { json: {} })).items[0];
  expect(proposal.pricing.totalCents).toBe(3000);
  expect(proposal.pricing.terms.calculation).toEqual({ id: first.id, version: 1 });
  const pdf = await api.request(`/api/honorarios/${proposal.id}/proposal?format=pdf&version=1`);
  expect(pdf.status).toBe(200);
  expect(Buffer.from(await pdf.arrayBuffer()).subarray(0, 5).toString()).toBe('%PDF-');
  await screen.getByText('Registrar contratação e gerar parcelas', { exact: true }).tap();
  await screen.getByLabel('Componente 1: primeiro vencimento').fill('2026-01-31');
  await screen.getByLabel('Componente 1: parcelas', { exact: true }).fill('3');
  await screen.getByLabel('Componente 1: evidência da contratação ou êxito').fill('Contrato aceito e arquivado pelo advogado.');
  await screen.getByRole('button', 'Gerar parcelas deste componente').tap();
  await expect(screen.getByRole('link', 'Abrir recebimentos')).toBeVisible();
  const billed = feeQuoteListDto.parse(await api.json('/api/honorarios/quote-list', { json: {} })).items[0];
  const agreement = honorarioDetailDto.parse(await api.json('/api/honorarios/get', { json: { agreementId: billed.billed[0].agreementId } }));
  expect(agreement.installments.map(row => row.dueOn)).toEqual(['2026-01-31', '2026-02-28', '2026-03-31']);
  expect(agreement.agreement.pricing?.reference?.uf).toBe('RS');
  await noOverflow();
  await browser.setViewport({ width: 390, height: 844 });
  await noOverflow();
  await app.screenshot('proposta-mobile');
  await app.open('/app/calc');
  await screen.getByRole('button', /^Tributário/).tap();
  await screen.getByLabel('Data-base', { exact: true }).fill('2025-03-20');
  await screen.getByLabel('Principal (R$)', { exact: true }).fill('1.000,00');
  await screen.getByLabel('Vencimento legal ou recolhimento indevido').fill('2025-03-10');
  await screen.getByLabel('Primeiro dia útil da mora (débito)').fill('2025-03-11');
  await screen.getByLabel('Tributo, período e fundamento do débito ou crédito').fill('Débito federal comum; vencimento e primeiro dia útil conferidos.');
  await screen.getByRole('button', 'Salvar cálculo', { exact: true }).tap();
  await expect(screen.getByTestId('calc-total')).toHaveText(/1\.033,00/);
  await noOverflow();
  await app.screenshot('calc-tributario-mobile');
  await screen.getByRole('button', 'Revisar parâmetros').tap();
  await noOverflow();

  let release!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  await browser.route('**/api/calc/list', async route => { await held; await route.fulfill({ status: 503, json: { error: 'Consulta de cálculos indisponível na validação.' } }); });
  await browser.goto('/app/calc', { waitUntil: 'domcontentloaded' });
  await expect(screen.getByText('Carregando cálculos…').first()).toBeVisible();
  release();
  await expect(screen.getByRole('alert').filter({ hasText: 'Consulta de cálculos indisponível' })).toBeVisible();
  await browser.unroute('**/api/calc/list');
  await screen.getByRole('button', 'Atualizar', { exact: true }).tap();
  await expect(screen.getByRole('button', /Restituição de cobrança/)).toBeVisible();
  await noOverflow();
});
