import { randomUUID } from 'node:crypto';
import { expect } from 'e2e';
import { test, overflowsHorizontally } from './support/fixtures';
import { ApiSession, uniqueAccount } from './support/accounts';
import { signInWithSession } from './support/sign-in';
import type { CaseTask } from '../src/lib/case-tasks/contracts';

test('caso compartilhado: tarefas reais, conflito preservado, honorários, atividade e política no celular', {timeout:240_000}, async ({app,screen,browser,sql})=>{
  const ownerAccount=uniqueAccount('Dona do caso'),guestAccount=uniqueAccount('Participante do caso');
  const owner=await new ApiSession(app.baseUrl!).signIn(ownerAccount),guest=await new ApiSession(app.baseUrl!).signIn(guestAccount);
  const {case:record}=await owner.json<{case:{id:string}}>('/api/vault/cases',{json:{name:'Caso de colaboração real'}});
  const invitation=await owner.json<{id:string}>('/api/collaboration',{json:{action:'invite',invitation:{email:guestAccount.email}}});
  await guest.json('/api/collaboration',{json:{action:'respond',id:invitation.id,accept:true}});
  const {viewerId:guestId}=await guest.json<{viewerId:string}>('/api/collaboration');
  await owner.json('/api/collaboration',{json:{action:'participant',caseId:record.id,userId:guestId,add:true}});
  await owner.json('/api/agenda/activities/create',{json:{kind:'task',title:'Tarefa pessoal invisível',caseId:record.id,idempotencyKey:randomUUID()}});
  const tasksUrl=`/api/cases/${record.id}/tasks`,href=`/app/vault/cases/${record.id}`;
  const tasks=async()=>(await guest.json<{tasks:CaseTask[]}>(tasksUrl)).tasks;
  const taskInput=(task:CaseTask)=>({title:task.title,notes:task.notes,status:task.status,dueOn:task.dueOn,assigneeId:task.assigneeId,version:task.version});
  const {client}=await guest.json<{client:{id:string}}>('/api/agenda/clients/create',{json:{name:'Cliente particular da participante',idempotencyKey:randomUUID()}});
  await guest.json('/api/honorarios/create',{json:{clientId:client.id,caseId:record.id,title:'Honorário compartilhado',notes:'Nota particular financeira',installments:[{dueOn:'2026-10-15',amountCents:25000}],idempotencyKey:randomUUID()}});
  expect(await tasks()).toHaveLength(0);
  await guest.json(`/api/cases/${record.id}/honorarios`);
  await guest.json(`/api/cases/${record.id}/activity`);
  await guest.json(`/api/cases/${record.id}/policy`);
  await signInWithSession({app,screen,browser},guest);
  await app.open(href+'?section=tasks');
  await expect(screen.getByText('Nenhuma tarefa aberta neste caso.')).toBeVisible();
  await expect(screen.getByText('Tarefa pessoal invisível')).toHaveCount(0);
  const create=screen.getByRole('button','Nova tarefa',{exact:true});await create.focus();await browser.keyboard.press('Enter');
  const title=screen.getByLabel('Título da tarefa');await expect(title).toBeFocused();
  await title.fill('Conferir documentos');await screen.getByLabel('Descrição da tarefa').fill('Conferir os documentos em conjunto.');
  await screen.getByLabel('Responsável',{exact:true}).selectOption({value:guestId});
  await screen.getByLabel('Prazo',{exact:true}).fill('2026-10-14');
  await screen.getByRole('button','Salvar tarefa',{exact:true}).tap();
  await expect(screen.getByRole('article','Conferir documentos')).toBeVisible();
  let task=(await tasks())[0];expect(task).toMatchObject({assigneeId:guestId,visibility:'case',version:1});
  expect(await sql('SELECT office_id,visibility FROM agenda_activity WHERE id=$1',[task.id])).toMatchObject([{visibility:'case'}]);
  await screen.getByRole('article','Conferir documentos').getByRole('button','Editar tarefa').tap();
  await title.fill('Meu rascunho preservado');
  await owner.json(tasksUrl+'/'+task.id,{method:'PUT',json:{...taskInput(task),notes:'Edição concorrente real'}});
  await screen.getByRole('button','Salvar tarefa',{exact:true}).tap();
  await expect(screen.getByRole('region','Tarefas compartilhadas').getByRole('alert')).toContainText('Esta tarefa mudou');await expect(title).toHaveValue('Meu rascunho preservado');
  await screen.getByRole('button','Atualizar versão e manter rascunho').tap();await expect(title).toHaveValue('Meu rascunho preservado');
  await screen.getByRole('button','Salvar tarefa',{exact:true}).tap();
  await expect(screen.getByRole('article','Meu rascunho preservado')).toBeVisible();task=(await tasks())[0];expect(task.version).toBe(3);
  await app.screenshot('caso-tarefas-desktop');
  await browser.setViewport({width:390,height:844});expect(await browser.evaluate(overflowsHorizontally)).toBe(false);
  const sections=screen.getByRole('group','Seção do caso');
  await sections.getByRole('button','Honorários',{exact:true}).tap();
  await expect(screen.getByText('Honorário compartilhado',{exact:true})).toBeVisible();
  await expect(screen.getByText('Nota particular financeira')).toHaveCount(0);
  await expect(screen.getByText('Cliente particular da participante')).toHaveCount(0);
  await expect(screen.getByRole('link','Gerenciar honorário')).toBeVisible();await app.screenshot('caso-honorarios-mobile');
  await sections.getByRole('button','Atividade',{exact:true}).tap();
  await expect(screen.getByRole('region','Atividade do caso')).toContainText('Meu rascunho preservado');
  await expect(screen.getByText('Tarefa pessoal invisível')).toHaveCount(0);
  await app.screenshot('caso-atividade-mobile');
  await sections.getByRole('button','Mais seções do caso',{exact:true}).tap();
  await screen.getByRole('menuitem','Participantes',{exact:true}).tap();
  await expect(screen.getByRole('checkbox','O Lume pode trabalhar neste caso')).toBeDisabled();
  await app.screenshot('caso-participantes-mobile');
  await signInWithSession({app,screen,browser},owner);await app.open(href+'?section=participants');
  const policy=screen.getByRole('checkbox','O Lume pode trabalhar neste caso');await policy.focus();await browser.keyboard.press('Space');
  await expect.poll(async()=>(await owner.json<{enabled:boolean}>(`/api/cases/${record.id}/policy`)).enabled).toBe(false);
  await app.screenshot('caso-politica-desligada-mobile');
  await signInWithSession({app,screen,browser},guest);await app.open(href+'?section=tasks');
  await screen.getByRole('article','Meu rascunho preservado').getByRole('button','Pedir ao Lume').tap();
  await expect(screen.getByRole('region','Tarefas compartilhadas').getByRole('alert')).toContainText('O Lume não está disponível neste caso');
  await screen.getByRole('article','Meu rascunho preservado').getByRole('button','Concluir',{exact:true}).tap();
  await expect(screen.getByText('Nenhuma tarefa aberta neste caso.')).toBeVisible();
  await screen.getByRole('button','Arquivadas',{exact:true}).tap();await expect(screen.getByRole('article','Meu rascunho preservado')).toContainText('Concluída');
  expect(await browser.evaluate(overflowsHorizontally)).toBe(false);await app.screenshot('caso-tarefas-humanas-mobile');
  await owner.json('/api/collaboration',{json:{action:'participant',caseId:record.id,userId:guestId,add:false}});
  expect((await guest.request(tasksUrl)).status).toBe(404);expect((await guest.request(`/api/cases/${record.id}/honorarios`)).status).toBe(404);
});
