import { test, overflowsHorizontally } from './support/fixtures';
import { expect } from 'e2e';
import { ApiSession, uniqueAccount } from './support/accounts';
import { seedConversationDocument } from './support/seed';
import { signInWithSession } from './support/sign-in';

test('Artefatos pertence ao caso e preserva documentos privados e cópias do Cofre', async ({ app, screen, browser, sql }) => {
  const account = uniqueAccount('Artefatos');
  const api = await new ApiSession(app.baseUrl!).signIn(account);
  const { case: selectedCase } = await api.json<{ case: { id: string } }>('/api/vault/cases', { json: { name: 'Caso dos artefatos' } });
  const { case: otherCase } = await api.json<{ case: { id: string } }>('/api/vault/cases', { json: { name: 'Outro caso' } });
  const { folder } = await api.json<{ folder: { id: string } }>('/api/vault/folders', { json: { caseId: selectedCase.id, name: 'Pasta particular', visibility: 'private' } });
  const { conversation } = await api.json<{ conversation: { id: string } }>('/api/conversations', { json: {} });
  const artifactId = await seedConversationDocument(account.email, conversation.id, 'Parecer societario', '# Parecer\n\nTexto para revisao.');
  const saved = await api.request('/api/conversations/' + conversation.id + '/artifacts', { json: { source: 'document', id: artifactId, version: 1, format: 'docx', scope: 'case', caseId: selectedCase.id, folderId: folder.id } });
  expect(saved.status).toBe(200);
  await signInWithSession({ app, screen, browser }, api);
  await app.open('/app/vault/cases/' + selectedCase.id);
  await screen.getByRole('group', 'Seção do caso').getByRole('button', 'Artefatos').tap();
  const panel = screen.getByRole('region', 'Artefatos do caso');
  await expect(panel.getByRole('link', 'Parecer societario', { exact: false }).first()).toBeVisible();
  await expect(panel.getByText('Privado, só você', { exact: false })).toBeVisible();
  await expect(panel.getByText('Salvo no Cofre', { exact: false })).toBeVisible();
  await panel.getByRole('button', 'Salvar no Cofre').tap();
  await panel.getByRole('radio', 'DOCX').tap();
  await panel.getByRole('combobox', 'Pasta').tap();
  await screen.getByRole('option', 'Pasta particular').tap();
  await panel.getByRole('button', 'Salvar', { exact: true }).tap();
  await expect(panel.getByRole('status')).toContainText('foi salvo');
  expect(await sql('SELECT count(*)::int AS n FROM vault_agent_origin WHERE source_id=$1', [artifactId])).toEqual([{ n: 1 }]);
  await browser.setViewport({ width: 390, height: 844 });
  expect(await browser.evaluate(overflowsHorizontally)).toBe(false);
  await app.screenshot('artefatos-do-caso-mobile');
  const unrelated = await api.json<{ artifacts: unknown[] }>('/api/vault/cases/' + otherCase.id + '/artifacts');
  expect(unrelated.artifacts).toEqual([]);
  const stranger = await new ApiSession(app.baseUrl!).signIn(uniqueAccount('Sem acesso'));
  expect((await stranger.request('/api/vault/cases/' + selectedCase.id + '/artifacts')).status).toBe(404);
  expect((await new ApiSession(app.baseUrl!).request('/api/vault/cases/' + selectedCase.id + '/artifacts')).status).toBe(401);
});
