import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

// Offline fallback, cache contents and multi-tab updates need browser emulation e2e does not
// expose; tests/pwa.test.ts covers the worker logic, scripts/verify-pwa-update.ts the update flow.
test('o manifesto, os ícones e o service worker do Lume estão publicados para instalação', async ({ app }) => {
  const get = (path: string) => fetch(new URL(path, app.baseUrl));
  const manifest = await (await get('/manifest.webmanifest')).json() as { name: string; short_name: string; display: string; start_url: string; icons: { src: string }[] };
  expect(manifest).toMatchObject({ name: 'Lume — Seu escritório', short_name: 'Lume', display: 'standalone', start_url: '/app' });
  expect(manifest.icons.length).toBeGreaterThan(0);
  for (const icon of manifest.icons) expect((await get(icon.src)).status, icon.src).toBe(200);
  const worker = await get('/sw.js');
  // The worker is generated by `pnpm build`; a dev server without a build has none.
  test.skip(worker.status === 404, 'public/sw.js só existe depois de pnpm build');
  expect(worker.headers.get('cache-control')).toContain('no-store');
});

test('instalar o Lume usa o convite do navegador ou explica como instalar, e o tema escuro ajusta a cor da barra', { session: 'admin' }, async ({ app, screen, browser }) => {
  await app.open('/app/command-center');
  await screen.getByRole('button', /^Conta de /).tap();
  const install = screen.getByRole('button', 'Instalar Lume', { visible: true });
  await expect(install).toBeVisible();
  // Chromium only offers the prompt to an installable, engaged page; fire it as the browser would.
  // `evaluate` runs in an isolated world, so a page script carries the `prompt` method into the
  // app's world. It repeats until the app handles the event, since hydration can finish after load.
  await expect.poll(() => browser.evaluate(() => {
    const script = document.createElement('script');
    script.textContent = `(() => {
      const event = Object.assign(new Event('beforeinstallprompt', { cancelable: true }), {
        prompt: () => { document.documentElement.dataset.installPromptCalled = 'true'; return Promise.resolve(); },
        userChoice: Promise.resolve({ outcome: 'dismissed' }),
      });
      window.dispatchEvent(event);
      document.documentElement.dataset.installOffered = String(event.defaultPrevented);
    })();`;
    document.head.append(script);
    script.remove();
    return document.documentElement.dataset.installOffered === 'true';
  }), { timeout: 30_000 }).toBe(true);
  await install.tap();
  await expect(browser.locator('html')).toHaveAttribute('data-install-prompt-called', 'true');
  // Once the prompt is spent, the button explains the manual steps instead.
  await install.tap();
  await expect(screen.getByRole('dialog', 'Instalar o Lume')).toBeVisible();
  await browser.keyboard.press('Escape');
  await expect(install).toBeFocused();

  const dark = await browser.evaluate(() => document.documentElement.classList.contains('dark'));
  if (!dark) await screen.getByRole('button', 'Usar tema escuro', { visible: true }).tap();
  await expect(browser).toHaveClass(browser.locator('html'), /\bdark\b/);
  await expect(browser.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#232323');
  await browser.reload();
  await expect(browser).toHaveClass(browser.locator('html'), /\bdark\b/);
});
