import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument, legalAddress, legalCompany, legalContact, type LegalSection } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Política de privacidade",
  description: "Como o Lume trata dados pessoais, documentos jurídicos e dados de integrações, e como exercer seus direitos.",
  alternates: { canonical: "https://lume.software/politica-privacidade" },
  robots: { index: true, follow: true },
};

const sections: LegalSection[] = [
  { id: "responsavel", title: "Quem responde pelo Lume", paragraphs: [
    <>O Lume é um serviço de {legalCompany}, CNPJ 57.717.768/0001-06, com endereço em {legalAddress}. Para exercer direitos ou tratar de privacidade e segurança, entre em contato por {legalContact}.</>,
    <>Esta política abrange o site lume.software, seus subdomínios operacionais e os recursos do Lume. Ela complementa os <Link href="/termos-de-uso">Termos e condições de uso</Link> e descreve as finalidades, os destinatários e os limites do tratamento. Não é uma autorização irrestrita para uso de dados nem substitui avisos específicos apresentados em uma integração.</>,
  ] },
  { id: "papeis", title: "Controladora e operadora", paragraphs: [
    "A Web Star Studio atua como controladora quando define as finalidades do tratamento necessário à gestão de contas, contratação, cobrança, segurança da plataforma, suporte e cumprimento de suas obrigações legais. Para esses tratamentos, responde diretamente pelas decisões que adota.",
    "Em relação aos documentos, casos, contatos e outros dados tratados por instrução de um escritório, a Web Star Studio atua, em regra, como operadora. O escritório ou profissional responsável define a finalidade do trabalho e a base legal pertinente. Os papéis dependem da operação concreta e não apenas do nome atribuído às partes em um contrato.",
    "Se o pedido disser respeito a dados sob controle de um escritório, poderemos encaminhá-lo ao responsável ou solicitar sua instrução, sem abandonar nossas obrigações legais. O uso de infraestrutura ou de serviços de IA não altera a titularidade dos documentos nem concede a outro escritório acesso ao seu acervo.",
  ] },
  { id: "dados", title: "Quais dados são tratados", paragraphs: [
    "Conta e vínculo profissional: nome, e-mail, nome do escritório, identificadores de conta, papéis, convites, permissões e preferências. A autenticação utiliza uma representação protegida da senha, e não sua gravação em texto aberto, além de sessões e registros necessários à segurança.",
    "Trabalho do escritório: documentos e anexos, texto extraído por OCR, índices de busca e representações vetoriais, casos, partes, contatos, tarefas, eventos, registros de honorários, conversas, instruções à IA, respostas e histórico de operações. O conteúdo pode incluir dados pessoais sensíveis e informações submetidas a sigilo, conforme o material fornecido pelo escritório.",
    "Integrações: identificadores de contas conectadas, permissões concedidas, tokens de acesso protegidos e dados efetivamente necessários ao recurso autorizado, como mensagens, metadados de e-mail, arquivos selecionados, eventos, participantes e resultados de consultas. O alcance varia conforme o serviço conectado.",
    "Voz e imagem: quando você usa o microfone, a câmera ou envia mídia, o conteúdo pode ser processado para transcrição, leitura e execução da solicitação. A permissão do dispositivo é solicitada quando necessária. Uma transcrição enviada na conversa passa a integrar seu conteúdo; arquivos de mídia importados ou recebidos por integrações seguem o tratamento do respectivo recurso.",
    "Contratação e suporte: dados de identificação e faturamento solicitados no fluxo de cobrança, identificadores e situação de pagamentos, solicitações de suporte e material que o usuário decida anexar, inclusive capturas de tela. Dados de pagamento informados diretamente ao processador seguem também seu próprio aviso de privacidade.",
    "Operação técnica: endereço IP quando disponível, informações do navegador e dispositivo, datas e horários, erros, identificadores de requisições, registros de acesso e execução, consumo dos recursos e inscrições para notificações. Os mecanismos de diagnóstico procuram reduzir a inclusão de conteúdo, credenciais e dados identificáveis, mas uma mensagem de erro ou material enviado pelo usuário também pode conter dados pessoais.",
  ] },
  { id: "origem", title: "Origem e necessidade dos dados", paragraphs: [
    "Os dados podem ser fornecidos pelo próprio titular, por integrantes do escritório, por participantes convidados, por uma conta externa conectada ou por fontes públicas consultadas no trabalho. A origem pública não torna os dados livres de proteção. O tratamento deve respeitar sua finalidade, necessidade e eventuais restrições de acesso.",
    "Dados necessários à criação da conta e à prestação do recurso solicitado são indicados no respectivo fluxo. A ausência desses dados pode impedir seu funcionamento. Conectar contas externas, importar arquivos e habilitar notificações são escolhas separadas do simples acesso ao site.",
    "Evite inserir documentos integrais quando um trecho suficiente atender à tarefa. O escritório deve avaliar a necessidade de remover identificadores e informações sensíveis antes de compartilhar conteúdo, inclusive em conversas com IA, pesquisa externa e solicitações de suporte.",
  ] },
  { id: "finalidades", title: "Finalidades e bases legais", paragraphs: [
    "Usamos os dados de conta e contratação para identificar usuários, administrar acessos, disponibilizar os recursos contratados, cobrar e prestar suporte. Conforme o caso, esses tratamentos se apoiam na execução de contrato ou de procedimentos solicitados pelo titular, nos termos do art. 7º, V, da LGPD.",
    "Registros necessários a obrigações fiscais, determinações de autoridades e guarda legal são tratados para cumprir obrigação legal ou regulatória. Informações necessárias à defesa em controvérsias podem ser conservadas para o exercício regular de direitos. Cada fundamento se limita aos dados e ao período necessários à sua finalidade.",
    "Segurança, prevenção de abuso e diagnóstico podem se apoiar em legítimo interesse quando cabível, mediante avaliação da necessidade e dos direitos do titular. Essa base não se aplica indistintamente a dados sensíveis. Quando uma finalidade depender de consentimento, ele será específico, informado e revogável, sem ser presumido pela mera leitura desta política.",
    "Nos dados tratados por conta do escritório, cabe ao controlador identificar a hipótese legal adequada, inclusive as previstas no art. 11 da LGPD para dados sensíveis. O exercício regular de direitos pode ser pertinente ao trabalho jurídico, mas não legitima coleta excessiva ou reutilização incompatível. A autorização técnica de uma integração não substitui a análise da base legal para dados de terceiros.",
  ] },
  { id: "inteligencia-artificial", title: "Documentos e inteligência artificial", paragraphs: [
    "Para responder a uma solicitação, o Lume pode encaminhar a provedores de IA as instruções, o contexto da conversa, trechos recuperados do acervo, imagens ou documentos necessários à tarefa e resultados de ferramentas. OCR, criação de índices e representações vetoriais também envolvem processamento do conteúdo. Esse processamento não é criptografia de ponta a ponta entre os usuários: os serviços envolvidos precisam acessar os dados necessários à execução.",
    "Os provedores podem variar conforme a configuração e a tarefa, incluindo OpenAI, Anthropic, Google Gemini e serviços acessados por OpenRouter. Recursos específicos podem usar TypeSafe para classificação e Exa para pesquisa externa. A presença de um fornecedor nessa relação não significa que todos os documentos sejam enviados a todos eles.",
    "O Lume não utiliza o conteúdo privado dos escritórios para treinar modelos próprios de uso geral. A execução de uma solicitação por um provedor externo não deve ser confundida com esse treinamento. Retenção técnica, prevenção de abuso e condições de tratamento pelo fornecedor dependem do serviço e da configuração contratados; não há promessa geral de retenção zero em todos os provedores. Informações sobre o processamento aplicável ao seu ambiente podem ser solicitadas pelo canal de privacidade.",
    "Respostas, classificações e sugestões apoiam o usuário e exigem revisão. O Lume não atribui a uma saída de IA o efeito de decisão jurídica vinculante sobre uma pessoa. Quando houver decisão tomada unicamente por tratamento automatizado que afete interesses do titular, poderão ser exercidos os direitos previstos no art. 20 da LGPD, conforme aplicáveis.",
  ] },
  { id: "google", title: "Dados das integrações Google", paragraphs: [
    "A conexão Google é opcional e separada do login no Lume. As permissões são solicitadas conforme os módulos escolhidos. Gmail permite consultar mensagens e preparar ou enviar comunicações autorizadas; Agenda permite consultar calendários e sincronizar ou alterar eventos; Drive e Docs permitem trabalhar com arquivos selecionados ou autorizados para o aplicativo. Regras do escritório e permissões da conta continuam aplicáveis.",
    "Quando a classificação de e-mails por IA estiver habilitada e for solicitada, assunto, remetente, trecho da mensagem, data e indicação de autoria podem ser processados pelo TypeSafe para sugerir categoria, prioridade e necessidade de resposta. Esse fluxo de classificação não envia o corpo completo nem anexos. Importações do Drive criam cópias independentes no destino escolhido no Cofre.",
    <>O uso e a transferência a outros aplicativos de informações recebidas das APIs Google ficam sujeitos à <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, incluindo os requisitos de uso limitado, e às regras aplicáveis ao Google Workspace. Esses dados devem ser usados somente para fornecer ou melhorar as funcionalidades voltadas ao usuário que justificaram o acesso. Não são destinados à publicidade personalizada, venda a intermediários de dados ou treinamento de modelos generalizados de IA.</>,
    "O acesso humano a dados Google se limita às hipóteses permitidas por essas regras, como autorização afirmativa para conteúdo específico, necessidade de segurança, cumprimento legal ou operações internas sobre dados agregados e anonimizados admitidas pela política. Transferências devem ser necessárias ao recurso solicitado ou enquadrar-se em outra hipótese expressamente permitida pelo Google.",
    <>Você pode desconectar a conta no Lume ou revogar o acesso nas <a href="https://myaccount.google.com/connections">conexões da sua Conta Google</a>. Isso interrompe novos acessos autorizados por essa conexão, mas não desfaz operações anteriores nem elimina automaticamente cópias que você importou para o escritório. Para solicitar eliminação de dados conservados pelo Lume, use {legalContact}, observados os direitos do escritório e as hipóteses legais de guarda.</>,
  ] },
  { id: "compartilhamento", title: "Destinatários e prestadores de serviço", paragraphs: [
    "O conteúdo pode ser acessado por integrantes e participantes a quem o escritório tenha concedido permissão. O envio de mensagem, convite, documento ou evento a um destinatário externo é um compartilhamento decorrente da operação autorizada. Confira os destinatários antes de concluir a ação.",
    "A infraestrutura utiliza serviços como Cloudflare para hospedagem, armazenamento, processamento e entrega, PlanetScale para banco de dados e Sentry para diagnóstico de erros. Provedores de IA recebem os dados necessários às tarefas descritas nesta política. Google atende às integrações conectadas; Zernio e os serviços de mensagens envolvidos atendem aos recursos de WhatsApp quando habilitados; AbacatePay processa cobranças quando utilizado.",
    "Os prestadores somente devem receber os dados necessários à atividade executada. Um fornecedor pode atuar como operador ou como controlador independente em finalidades próprias, como cumprimento de suas obrigações legais, conforme a operação. A Web Star Studio permanece responsável pelas obrigações que a legislação lhe atribui na escolha e utilização desses serviços.",
    "Dados também podem ser fornecidos a autoridades mediante fundamento legal válido ou conservados para exercício de direitos. Em reorganização societária, o tratamento deve manter as finalidades e salvaguardas aplicáveis e assegurar a transparência devida. Esta política não autoriza venda do acervo dos escritórios ou seu uso para publicidade comportamental.",
  ] },
  { id: "transferencias", title: "Processamento internacional", paragraphs: [
    "A infraestrutura distribuída, o suporte e os provedores integrados podem envolver processamento ou acesso fora do Brasil, inclusive nos Estados Unidos e em outros países em que operem os fornecedores contratados. A localização de um banco de dados no Brasil não significa que todas as operações do Lume ocorram no país.",
    <>Transferências internacionais devem observar a LGPD e o <a href="https://www.gov.br/anpd/pt-br/assuntos/assuntos-internacionais/transferencia-internacional-de-dados">regulamento da ANPD</a>, com mecanismo válido para a operação, como decisão de adequação ou garantias contratuais admitidas. A menção dessas possibilidades não equivale à afirmação de que um mesmo mecanismo foi adotado para todos os fornecedores. Você pode solicitar informações sobre destinatários, países, finalidade, duração e salvaguardas pertinentes ao seu tratamento por {legalContact}.</>,
  ] },
  { id: "seguranca", title: "Segurança e incidentes", paragraphs: [
    "O Lume utiliza HTTPS, proteção das senhas por hash, controles de sessão, verificação de permissões e separação lógica dos dados por escritório. Credenciais de integrações são protegidas no servidor. O acesso aos dados de negócio é condicionado à conta, ao vínculo com o escritório e às permissões pertinentes. Esses controles reduzem riscos, mas não tornam qualquer sistema imune a falhas.",
    "A segurança também depende da proteção dos dispositivos e credenciais e da revisão dos compartilhamentos pelo escritório. O serviço não se apresenta como sistema de criptografia de ponta a ponta nem como repositório com recuperação garantida de qualquer exclusão ou versão. Mantenha cópias independentes dos documentos essenciais.",
    "Ao identificar um incidente, a Web Star Studio deve avaliar o alcance, adotar medidas de contenção e cumprir as obrigações de comunicação. Quando atuar como operadora, deve informar o controlador e cooperar para as providências cabíveis. Quando lhe couber a comunicação à ANPD e aos titulares, observará os critérios e prazos legais e regulatórios aplicáveis. Suspeitas podem ser informadas pelo canal de privacidade, sem incluir senhas ou tokens na mensagem.",
  ] },
  { id: "retencao", title: "Conservação e eliminação", paragraphs: [
    "Dados de conta e conteúdo do escritório são conservados enquanto necessários à prestação do serviço e às instruções lícitas do controlador. Cancelar uma assinatura ou desconectar uma integração não elimina automaticamente todo o acervo. Pedidos de encerramento, exportação e exclusão precisam considerar a autoridade de quem solicita e os direitos de outros titulares e do escritório.",
    "Após o término da finalidade, os dados devem ser eliminados ou anonimizados, ressalvadas as hipóteses legais de conservação, como obrigações fiscais, exercício de direitos e preservação determinada por autoridade competente. A guarda residual deve ter finalidade definida e acesso limitado; não autoriza a reutilização do conteúdo para finalidades incompatíveis.",
    "Registros de acesso à aplicação sujeitos ao art. 15 do Marco Civil da Internet têm prazo legal de guarda de seis meses, sem prejuízo de ordem válida de preservação. Esse prazo não se estende indistintamente a mensagens e documentos. Registros fiscais, contratuais e de incidentes seguem os prazos legais aplicáveis à respectiva categoria.",
    "A eliminação pode envolver originais, índices, representações derivadas, caches e cópias técnicas. Cópias de segurança ou registros sujeitos a retenção não são necessariamente apagados no mesmo instante que o dado ativo. Ao atender um pedido, informaremos o alcance, as etapas pertinentes e eventual fundamento para conservação. Informações sobre o prazo aplicável a uma categoria específica podem ser solicitadas pelo canal de privacidade.",
  ] },
  { id: "direitos", title: "Seus direitos e como exercê-los", paragraphs: [
    "Nos termos da LGPD, você pode solicitar confirmação de tratamento, acesso, correção e informações sobre compartilhamento. Pode pedir anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade, além de portabilidade conforme a regulamentação e resguardados os segredos comercial e industrial.",
    "Também pode solicitar eliminação de dados tratados com consentimento, observadas as exceções legais, revogar consentimento, informar-se sobre a possibilidade de não consentir e suas consequências e opor-se ao tratamento nas hipóteses legais. Permanecem preservados os direitos relativos a decisões exclusivamente automatizadas e a apresentação de reclamação à ANPD e aos órgãos competentes.",
    <>Envie o pedido para {legalContact}, indicando sua relação com o Lume e o direito que deseja exercer. Poderemos solicitar elementos proporcionais para confirmar sua identidade ou representação e impedir a divulgação a terceiros. Não envie senhas, tokens ou cópias integrais de documentos sem orientação. O exercício desses direitos é gratuito.</>,
    "A confirmação de existência ou o acesso será providenciado em formato simplificado imediatamente, quando possível, ou por declaração clara e completa no prazo legal de até quinze dias, conforme o art. 19 da LGPD. Outros pedidos observam os prazos aplicáveis à sua natureza. Eventual impossibilidade, necessidade de encaminhamento ao controlador ou motivo legal de recusa será explicado, sem prometer uma prorrogação automática não prevista em lei.",
  ] },
  { id: "cookies", title: "Cookies, armazenamento local e notificações", paragraphs: [
    "O Lume utiliza cookies de autenticação, sessão e seleção de escritório, além de armazenamento local para preferências de interface e recursos da aplicação. Tecnologias de cache podem conservar recursos do aplicativo no dispositivo. Elas não devem ser confundidas com uma cópia completa e atualizada de todos os documentos do escritório.",
    "Você pode gerenciar esses dados nas configurações do navegador. Bloquear ou apagar cookies necessários pode encerrar a sessão ou impedir funções. Em dispositivo compartilhado, encerre a sessão e proteja arquivos baixados. Notificações do navegador dependem de permissão e podem ser desativadas nas configurações do dispositivo ou navegador.",
    "Esta política não presume consentimento para cookies publicitários ou rastreamento opcional. Se forem introduzidas tecnologias que dependam de consentimento, a finalidade e as opções pertinentes deverão ser apresentadas antes de sua ativação. Ferramentas de diagnóstico técnico são utilizadas para investigar erros e desempenho, conforme as finalidades descritas neste documento.",
  ] },
  { id: "menores", title: "Dados de crianças e adolescentes", paragraphs: [
    "O Lume não é dirigido ao cadastro de menores de 18 anos. Entretanto, documentos jurídicos inseridos por um escritório podem conter dados de crianças e adolescentes. O controlador deve observar seu melhor interesse, a necessidade do tratamento e os requisitos específicos aplicáveis, inclusive quando o fundamento jurídico não for consentimento.",
    "O fato de um dado integrar um processo não afasta esses cuidados. Caso identifique tratamento inadequado, entre em contato para avaliação e adoção das medidas cabíveis, respeitadas as obrigações de guarda e os direitos envolvidos.",
  ] },
  { id: "atualizacoes", title: "Atualizações e contato", paragraphs: [
    "Mudanças de recursos, fornecedores ou exigências legais podem exigir atualização desta política. A data e a versão constam no início do documento. Alterações materiais serão comunicadas por meio adequado ao seu impacto. Novas finalidades incompatíveis não serão legitimadas por uma alteração silenciosa do texto.",
    <>Para dúvidas, pedidos de titulares e informações sobre o tratamento no seu ambiente, escreva para {legalContact}, o canal de privacidade do Lume. Você também pode solicitar esclarecimentos sobre a atuação da Web Star Studio e do escritório responsável pelos seus dados.</>,
  ] },
];

export default function PrivacyPage() {
  return <LegalDocument title="Política de privacidade" introduction="Como tratamos dados de contas, documentos e integrações, quem participa desse tratamento e quais escolhas e direitos você tem." sections={sections} />;
}
