#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Staging values live apart from local development. .gitignore already covers .env.*
ENV_FILE=".env.staging"

CF_ACCOUNT="bf552f67bcf46921dbe4137ee0ff8980"
R2_BUCKET_NAME="k5-vault-staging"
VECTORIZE_INDEX_NAME="k5-knowledge-staging"

banner "Lume staging: Cloudflare R2 + Vectorize + Neon Postgres"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: enable R2"
say "R2 stores the Vault originals. It cannot be switched on through the API,"
say "so this is the one step that has to happen in the dashboard."
open_url "https://dash.cloudflare.com/${CF_ACCOUNT}/r2/overview"
step "If you see a purchase screen, accept the R2 plan. The free tier is enough to start."
step "Wait until the page shows the bucket list instead of the enable prompt."
note "Nothing is captured here; the next stage checks it worked."
pause "Done? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: create the Vault bucket"
say "One bucket holds every office's originals. Objects are keyed"
say "office/document/uuid, so a key cannot address another office's file."
open_url "https://dash.cloudflare.com/${CF_ACCOUNT}/r2/new"
step "Bucket name: ${R2_BUCKET_NAME}"
step "Location: Automatic. Leave public access OFF - the app serves downloads through its own authenticated route."
ask R2_BUCKET "Bucket name you created [${R2_BUCKET_NAME}]:"
[[ -z "$R2_BUCKET" ]] && R2_BUCKET="$R2_BUCKET_NAME"
write_env R2_BUCKET "$R2_BUCKET"
write_env R2_ACCOUNT_ID "$CF_ACCOUNT"
set_secret R2_BUCKET "$R2_BUCKET"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: R2 access keys"
say "The app talks to R2 over the S3-compatible API, which needs its own key pair."
open_url "https://dash.cloudflare.com/${CF_ACCOUNT}/r2/api-tokens"
step "Create an Account API token."
step "Permission: Object Read & Write."
step "Scope it to the single bucket ${R2_BUCKET} rather than all buckets."
step "Create, then copy the Access Key ID and the Secret Access Key from the result page."
warn "The secret is shown once. Copy it before leaving the page."
ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key:"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
set_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
set_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: API token for Vectorize"
say "The index ${VECTORIZE_INDEX_NAME} already exists (1536 dimensions, cosine,"
say "with metadata indexes on generationId and documentId so the scope filter"
say "is pushed into the query instead of trimming results after topK)."
say ""
say "This token lets the app read and write vectors in it."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token."
step "Name: k5-staging-vectorize"
step "Permission: Account → Vectorize → Edit."
step "Account Resources: include only this account."
step "Create, then copy the token value."
warn "The token is shown once."
ask_secret CF_API_TOKEN "Paste the API token:"
write_env CF_API_TOKEN "$CF_API_TOKEN"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT"
write_env VECTORIZE_INDEX "$VECTORIZE_INDEX_NAME"
write_env VECTOR_INDEX_BACKEND "vectorize"
set_secret CF_API_TOKEN "$CF_API_TOKEN"
set_secret CF_ACCOUNT_ID "$CF_ACCOUNT"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Neon: Postgres with pgvector"
say "Cloudflare has no first-party Postgres. Neon gives a free tier, pgvector,"
say "and branch databases that map onto per-pull-request previews later."
open_url "https://console.neon.tech/signup"
step "Sign up or sign in (GitHub login works)."
step "Create a project named k5-staging."
step "Postgres version: 17. Region: pick the one closest to your users."
step "On the project dashboard, open Connection Details."
step "Choose the pooled connection string and copy it."
note "It looks like postgresql://user:password@ep-xxx-pooler.region.aws.neon.tech/neondb?sslmode=require"
ask_secret DATABASE_URL "Paste the Neon connection string:"
write_env DATABASE_URL "$DATABASE_URL"
set_secret DATABASE_URL "$DATABASE_URL"
say ""
step "Now open the Neon SQL Editor and run:  CREATE EXTENSION IF NOT EXISTS vector;"
note "The app also issues this on first use, but running it now fails fast if the plan lacks it."
open_url "https://console.neon.tech/app/projects"
pause "Extension created? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: Hyperdrive in front of Neon"
say "Hyperdrive pools connections and caches queries, so Workers reach Neon"
say "without opening a fresh connection per request. Needed once the app moves"
say "onto Workers; harmless to set up now."
open_url "https://dash.cloudflare.com/${CF_ACCOUNT}/workers/hyperdrive/create"
step "Choose 'Connect to an existing database'."
step "Paste the same Neon connection string from the previous stage."
step "Name: k5-staging-neon"
step "Create, then copy the Hyperdrive configuration ID shown on the detail page."
ask HYPERDRIVE_ID "Paste the Hyperdrive ID (Enter to skip for now):"
if [[ -n "$HYPERDRIVE_ID" ]]; then
  write_env HYPERDRIVE_ID "$HYPERDRIVE_ID"
  set_var HYPERDRIVE_ID "$HYPERDRIVE_ID"
else
  SKIPPED+=("Hyperdrive config (only needed when the app moves onto Workers)")
  note "Skipped. The pgvector adapter talks to Neon directly until then."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Application secrets for staging"
say "Two secrets the app needs, generated locally rather than typed by hand."
say ""
warn "K5_CREDENTIALS_KEY encrypts every stored provider credential."
warn "Lose it and those credentials cannot be recovered. Back up .env.staging."
if confirm "Generate fresh staging secrets now?"; then
  write_env BETTER_AUTH_SECRET "$(openssl rand -base64 48 | tr -d '\n')"
  write_env K5_CREDENTIALS_KEY "$(openssl rand -base64 32 | tr -d '\n')"
  set_secret BETTER_AUTH_SECRET "$(_existing BETTER_AUTH_SECRET)"
  set_secret K5_CREDENTIALS_KEY "$(_existing K5_CREDENTIALS_KEY)"
else
  SKIPPED+=("BETTER_AUTH_SECRET and K5_CREDENTIALS_KEY for staging")
fi
ask BETTER_AUTH_URL "Staging URL (e.g. https://staging.k5.app):"
[[ -n "$BETTER_AUTH_URL" ]] && write_env BETTER_AUTH_URL "$BETTER_AUTH_URL"

say ""
note "Verify the whole staging data plane with:"
note "  pnpm --filter @k5/web exec tsx scripts/verify-staging.ts"

finish
