import { spawn } from 'node:child_process';
import { readFileSync, mkdirSync, createWriteStream, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const pointer=JSON.parse(readFileSync(join(tmpdir(),'lume-verify-current.json'),'utf8'));
const state=JSON.parse(readFileSync(join(pointer.runDir,'state.json'),'utf8'));
if(state.runId!=='20261006T234247-d88728'||state.port!==62541||state.pgPort!==62542||state.status!=='ready')throw Error('Wrong isolated run');
const command=process.argv[2];if(!['test','build','lint','typecheck'].includes(command))throw Error('Invalid check');
const files=process.argv.slice(3);if(files.length&&(command!=='test'||files.some(file=>!/^tests\/[a-z0-9-]+\.test\.ts$/.test(file)||!existsSync(new URL('../apps/web/'+file,import.meta.url)))))throw Error('Invalid diagnostic test files');
const isolated=Object.fromEntries(readFileSync(join(pointer.runDir,'verify.env'),'utf8').trim().split(/\r?\n/).map(line=>{const index=line.indexOf('=');return[line.slice(0,index),line.slice(index+1)];}));
const example=readFileSync(new URL('../apps/web/.env.example',import.meta.url),'utf8');
const names=[...example.matchAll(/^#?\s*([A-Z][A-Z_0-9]+)=/gm)].map(match=>match[1]);
const blank=Object.fromEntries([...names,'SENTRY_AUTH_TOKEN','SENTRY_REQUIRE_SOURCEMAPS','SENTRY_DSN','NEXT_PUBLIC_SENTRY_DSN'].filter(name=>!(name in isolated)).map(name=>[name,'']));
const testDefaults=command==='test'?{GOOGLE_OAUTH_CLIENT_ID:'test-client.apps.googleusercontent.com',GOOGLE_OAUTH_CLIENT_SECRET:'test-client-secret'}:{};
const output=join(state.evidenceDir,`round3-root-${command}-${Date.now()}`);mkdirSync(output,{recursive:true});
const log=createWriteStream(join(output,'output.log'));
const nodeOptions = `--max-old-space-size=6144${command === 'test' ? ` --import=${new URL('./lume-no-external-test-traffic.mjs', import.meta.url).href}` : ''}`;
const child=spawn(process.env.ComSpec ?? 'cmd.exe',['/d','/s','/c',`pnpm ${command} --env-mode=loose${files.length?' -- '+files.join(' '):''}`],{cwd:new URL('../',import.meta.url),windowsHide:true,env:{...process.env,...blank,...isolated,...testDefaults,NODE_OPTIONS:nodeOptions,K5_ENV_FILE:join(pointer.runDir,'verify.env'),DATABASE_URL:state.databaseUrl,DATABASE_URL_UNPOOLED:state.databaseUrl,TEST_DATABASE_URL:state.databaseUrl,K5_TEST_CONCURRENCY:'1',VAULT_STORAGE_PATH:join(pointer.runDir,'round3-build-objects'),...(command==='build'?{K5_NEXT_DIST_DIR:'.next-agent-verify'}:{})},stdio:['ignore','pipe','pipe']});
for(const pipe of [child.stdout,child.stderr])pipe.on('data',data=>{log.write(data);process.stdout.write(data)});
const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('exit',resolve)});log.end();console.log(JSON.stringify({output,exitCode:code}));process.exitCode=code??1;
