import { remoteObjectStorage } from '@/lib/storage';
import 'server-only';
import { createHash, randomUUID } from 'node:crypto';
import { link, mkdir, readFile, readdir, stat, unlink, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { database } from '@/lib/database';
import { assertResearchStorageRuntime } from './runtime';

/** Corpus bytes are content-addressed, without an invented office id or a Vault key. */
const KEY = /^research\/sha256\/[0-9a-f]{2}\/[0-9a-f]{64}\.(pdf|html|txt|json|zip)$/;
const root = resolve(process.env.RESEARCH_STORAGE_PATH ?? '.data/research-objects');

type ResearchExtension = 'pdf' | 'html' | 'txt' | 'json' | 'zip';

export function researchStorageKey(bytes: Uint8Array, extension: ResearchExtension): string {
  const hash = createHash('sha256').update(bytes).digest('hex');
  return `research/sha256/${hash.slice(0, 2)}/${hash}.${extension}`;
}
function assertResearchKey(key:string): string {
  if (!KEY.test(key)) throw new Error('Chave de armazenamento de pesquisa inválida.');
  return key;
}
function pathFor(key: string): string {
  if (!KEY.test(key)) throw new Error('Chave de armazenamento de pesquisa inválida.');
  const path = resolve(root, key);
  if (!path.startsWith(`${root}${sep}`)) throw new Error('Chave de armazenamento de pesquisa inválida.');
  return path;
}
export async function putResearchOriginal(bytes: Uint8Array, extension: ResearchExtension): Promise<string> {
  await assertResearchStorageRuntime();
  const key = researchStorageKey(bytes, extension);
  const remote = await remoteObjectStorage(assertResearchKey);
  if (remote) {
    await remote.put(key,Buffer.from(bytes));
    const existing = await remote.get(key);
    if (researchStorageKey(existing,extension)!==key) throw new Error('Objeto de pesquisa corrompido.');
    return key;
  }
  const path = pathFor(key);
  const directory = dirname(path);
  await mkdir(directory, { recursive: true });
  const temporary = resolve(directory, `.staging-${randomUUID()}`);
  try {
    await writeFile(temporary, bytes, { flag: 'wx', mode: 0o600 });
    // link publishes a complete file without overwriting another worker's valid object.
    try { await link(temporary, path); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error; }
  } finally {
    await unlink(temporary).catch((error: NodeJS.ErrnoException) => { if (error.code !== 'ENOENT') throw error; });
  }
  const existing = await readFile(path);
  if (createHash('sha256').update(existing).digest('hex') !== key.match(/[0-9a-f]{64}/)?.[0]) {
    throw new Error('Objeto de pesquisa corrompido.');
  }
  return key;
}
export async function sweepResearchStaging(maxAgeMs = 60 * 60 * 1000): Promise<number> {
  await assertResearchStorageRuntime();
  if (await remoteObjectStorage(assertResearchKey)) return 0;
  let removed = 0;
  // Only staging files generated by this module under the controlled corpus directory.
  async function visit(directory: string): Promise<void> {
    let entries;
    try { entries = await readdir(directory, { withFileTypes: true }); }
    catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return; throw error; }
    for (const entry of entries) {
      const child = resolve(directory, entry.name);
      if (entry.isDirectory()) await visit(child);
      else if (entry.isFile() && /^\.staging-[0-9a-f-]{36}$/.test(entry.name)) {
        const age = Date.now() - (await stat(child)).mtimeMs;
        if (age > maxAgeMs) { await unlink(child); removed++; }
      }
    }
  }
  await visit(root);
  return removed;
}
export async function sweepResearchOrphans(maxAgeMs = 24 * 60 * 60 * 1000): Promise<number> {
  await assertResearchStorageRuntime();
  if (await remoteObjectStorage(assertResearchKey)) return 0;
  let removed=0;
  const base=resolve(root,'research','sha256');
  let shards;
  try { shards=await readdir(base,{withFileTypes:true}); }
  catch (error) { if ((error as NodeJS.ErrnoException).code==='ENOENT') return 0; throw error; }
  for (const shard of shards) {
    if (!shard.isDirectory() || !/^[0-9a-f]{2}$/.test(shard.name)) continue;
    const directory=resolve(base,shard.name);
    for (const entry of await readdir(directory,{withFileTypes:true})) {
      if (!entry.isFile()) continue;
      const key=`research/sha256/${shard.name}/${entry.name}`;
      if (!KEY.test(key)) continue;
      const file=pathFor(key);
      if (Date.now()-(await stat(file)).mtimeMs<maxAgeMs) continue;
      const used=await database.prepare('SELECT 1 FROM research_material_version WHERE storage_key=? LIMIT 1').get(key);
      // STJ keeps the downloaded resource only in its durable checkpoint while parsing batches.
      const checkpointed=await database.prepare(`SELECT 1 FROM research_source_resource
        WHERE original_storage_key=? OR
          (checkpoint IS JSON AND ((checkpoint::jsonb->>'storageKey')=?
            OR (checkpoint::jsonb->>'originalStorageKey')=?)) LIMIT 1`).get(key,key,key);
      if (!used && !checkpointed) { await unlink(file); removed++; }
    }
  }
  return removed;
}
export async function getResearchOriginal(key: string): Promise<Buffer> {
  await assertResearchStorageRuntime();
  assertResearchKey(key);
  const remote = await remoteObjectStorage(assertResearchKey);
  const bytes = remote ? await remote.get(key) : await readFile(pathFor(key));
  if (researchStorageKey(bytes, key.slice(key.lastIndexOf('.') + 1) as ResearchExtension) !== key) {
    throw new Error('Objeto de pesquisa corrompido.');
  }
  return bytes;
}
